# carta_vini.py
# LA CARTA DEI VINI PER CATEGORIE — il canovaccio del sommelier.
# Non tecniche di vinificazione (quelle sono i fenomeni), ma i vini per tipologia/territorio
# con profilo e abbinamenti col cibo. Serve a costruire la carta e a dialogare col menu.

CARTA_VINI = {
    "Rossi corposi": {
        "descrizione": "Struttura, tannino, alcol. Reggono piatti ricchi e grassi.",
        "vini": [
            {"nome": "Barolo", "territorio": "Piemonte", "vitigno": "Nebbiolo",
             "profilo": "tannino alto, acidità viva, note di rosa, catrame, tabacco",
             "abbina": "brasati, selvaggina, formaggi stagionati, tartufo",
             "perche": "il tannino sgrassa le carni ricche, l'acidità pulisce il palato dal grasso"},
            {"nome": "Amarone della Valpolicella", "territorio": "Veneto", "vitigno": "Corvina",
             "profilo": "corpo pieno, alcol 15-16%, frutta sotto spirito, cioccolato",
             "abbina": "brasati, selvaggina, formaggi erborinati",
             "perche": "l'alcol e la concentrazione reggono piatti intensi e lunghe cotture"},
            {"nome": "Brunello di Montalcino", "territorio": "Toscana", "vitigno": "Sangiovese",
             "profilo": "tannino elegante, acidità, ciliegia, cuoio, spezie",
             "abbina": "fiorentina, cinghiale, arrosti, pecorino stagionato",
             "perche": "acidità e tannino tagliano il grasso della carne rossa alla brace"},
            {"nome": "Taurasi", "territorio": "Campania", "vitigno": "Aglianico",
             "profilo": "tannino robusto, acidità, frutta scura, note balsamiche",
             "abbina": "ragù di carne, agnello, formaggi stagionati",
             "perche": "il tannino deciso pulisce il palato da sughi grassi e carni saporite"},
        ],
    },
    "Rossi medi": {
        "descrizione": "Equilibrio tra frutto e struttura. Versatili a tavola.",
        "vini": [
            {"nome": "Chianti Classico", "territorio": "Toscana", "vitigno": "Sangiovese",
             "profilo": "acidità viva, tannino medio, ciliegia, viola, erbe",
             "abbina": "pasta al ragù, pizza, salumi, carni bianche",
             "perche": "l'acidità del Sangiovese pulisce il palato dal pomodoro e dai grassi"},
            {"nome": "Valpolicella", "territorio": "Veneto", "vitigno": "Corvina",
             "profilo": "fruttato, fresco, tannino leggero, ciliegia",
             "abbina": "primi, salumi, carni bianche",
             "perche": "la freschezza accompagna senza sovrastare piatti di media intensità"},
            {"nome": "Montepulciano d'Abruzzo", "territorio": "Abruzzo", "vitigno": "Montepulciano",
             "profilo": "morbido, frutta matura, tannino dolce",
             "abbina": "arrosticini, pasta al forno, pizza",
             "perche": "morbidezza e frutto reggono piatti saporiti senza spigoli"},
            {"nome": "Cannonau", "territorio": "Sardegna", "vitigno": "Cannonau",
             "profilo": "caldo, frutta matura, macchia mediterranea, speziato",
             "abbina": "porceddu, agnello, formaggi sardi",
             "perche": "il calore e le note mediterranee legano con le carni alla brace"},
        ],
    },
    "Bianchi freschi": {
        "descrizione": "Acidità, mineralità, sapidità. Puliscono e rinfrescano.",
        "vini": [
            {"nome": "Vermentino", "territorio": "Sardegna / Liguria", "vitigno": "Vermentino",
             "profilo": "sapido, agrumi, note saline, mandorla amara",
             "abbina": "crudi di mare, pesce alla griglia, frutti di mare",
             "perche": "la sapidità richiama la salinità del mare, l'acidità pulisce"},
            {"nome": "Verdicchio", "territorio": "Marche", "vitigno": "Verdicchio",
             "profilo": "acidità, agrumi, mandorla, mineralità",
             "abbina": "brodetto di pesce, fritture, primi di mare",
             "perche": "l'acidità taglia il fritto e regge i sughi di pesce saporiti"},
            {"nome": "Falanghina", "territorio": "Campania", "vitigno": "Falanghina",
             "profilo": "fresco, floreale, agrumi, sapido",
             "abbina": "mozzarella, frittura di paranza, spaghetti a vongole",
             "perche": "freschezza e sapidità accompagnano il pesce e i latticini freschi"},
            {"nome": "Soave", "territorio": "Veneto", "vitigno": "Garganega",
             "profilo": "floreale, mandorla, fresco, delicato",
             "abbina": "risotti, pesce di lago, antipasti",
             "perche": "delicatezza che non copre piatti leggeri e cremosi"},
            {"nome": "Pinot Grigio", "territorio": "Friuli / Trentino", "vitigno": "Pinot Grigio",
             "profilo": "secco, agrumi, fresco, leggero",
             "abbina": "antipasti, pesce, primi leggeri",
             "perche": "versatile e pulito, non sovrasta i piatti delicati"},
        ],
    },
    "Bianchi strutturati": {
        "descrizione": "Corpo, complessità, spesso passaggio in legno. Reggono piatti ricchi.",
        "vini": [
            {"nome": "Fiano di Avellino", "territorio": "Campania", "vitigno": "Fiano",
             "profilo": "corpo, nocciola, miele, mineralità, evoluzione",
             "abbina": "pesce in umido, carni bianche, formaggi di media stagionatura",
             "perche": "la struttura regge piatti saporiti dove un bianco fresco cederebbe"},
            {"nome": "Greco di Tufo", "territorio": "Campania", "vitigno": "Greco",
             "profilo": "sapido, agrumi, pietra focaia, corpo",
             "abbina": "zuppe di pesce, crostacei, fritture importanti",
             "perche": "sapidità e corpo tengono testa a piatti di mare intensi"},
            {"nome": "Chardonnay in legno", "territorio": "vari", "vitigno": "Chardonnay",
             "profilo": "burroso, vaniglia, frutta matura, corpo pieno",
             "abbina": "pesce in salsa, carni bianche cremose, formaggi",
             "perche": "il corpo e le note di legno legano con salse e cotture ricche"},
        ],
    },
    "Bollicine": {
        "descrizione": "Effervescenza, acidità. Aperitivo e piatti fritti o grassi.",
        "vini": [
            {"nome": "Franciacorta", "territorio": "Lombardia", "vitigno": "Chardonnay/Pinot Nero",
             "profilo": "metodo classico, crosta di pane, agrumi, bollicina fine",
             "abbina": "aperitivo, crudi, fritture, tutto il pasto",
             "perche": "la bollicina e l'acidità puliscono il palato dal grasso e dal fritto"},
            {"nome": "Trento DOC", "territorio": "Trentino", "vitigno": "Chardonnay",
             "profilo": "metodo classico, fresco, montagna, mineralità",
             "abbina": "aperitivo, pesce, primi delicati",
             "perche": "freschezza alpina che sgrassa e rinfresca"},
            {"nome": "Prosecco", "territorio": "Veneto", "vitigno": "Glera",
             "profilo": "metodo Charmat, floreale, fruttato, beverino",
             "abbina": "aperitivo, antipasti, fritture leggere",
             "perche": "leggerezza e bollicina per l'aperitivo e i fritti"},
            {"nome": "Lambrusco", "territorio": "Emilia", "vitigno": "Lambrusco",
             "profilo": "rosso frizzante, fruttato, acidità",
             "abbina": "salumi, tortellini, gnocco fritto, pizza",
             "perche": "l'effervescenza e l'acidità tagliano il grasso dei salumi emiliani"},
        ],
    },
    "Rosati": {
        "descrizione": "Freschezza del bianco, frutto del rosso. Versatili d'estate.",
        "vini": [
            {"nome": "Cerasuolo d'Abruzzo", "territorio": "Abruzzo", "vitigno": "Montepulciano",
             "profilo": "ciliegia, fresco, sapido, corpo medio",
             "abbina": "zuppe di pesce, primi saporiti, salumi",
             "perche": "corpo e frutto reggono piatti dove un bianco sarebbe troppo leggero"},
            {"nome": "Rosato del Salento", "territorio": "Puglia", "vitigno": "Negroamaro",
             "profilo": "fruttato, caldo, fresco",
             "abbina": "pesce, primi di mare, verdure",
             "perche": "versatile su piatti mediterranei di media intensità"},
        ],
    },
    "Dolci e da meditazione": {
        "descrizione": "Zucchero, alcol, complessità. Dessert e formaggi erborinati.",
        "vini": [
            {"nome": "Passito di Pantelleria", "territorio": "Sicilia", "vitigno": "Zibibbo",
             "profilo": "dolce, albicocca, miele, frutta secca",
             "abbina": "pasticceria secca, formaggi erborinati",
             "perche": "la dolcezza contrasta il sale del formaggio, lega coi dolci"},
            {"nome": "Vin Santo", "territorio": "Toscana", "vitigno": "Trebbiano/Malvasia",
             "profilo": "dolce, frutta secca, miele, ossidativo",
             "abbina": "cantucci, pasticceria secca, formaggi",
             "perche": "abbinamento classico coi cantucci, dolcezza equilibrata"},
            {"nome": "Recioto della Valpolicella", "territorio": "Veneto", "vitigno": "Corvina",
             "profilo": "rosso dolce, frutta sotto spirito, cioccolato",
             "abbina": "dolci al cioccolato, pasticceria",
             "perche": "il frutto dolce e le note di cacao legano coi dolci al cioccolato"},
        ],
    },
}


# ── VINI DEL MONDO — aggiunti alle stesse categorie (carta internazionale) ──
VINI_MONDO = {
    "Rossi corposi": [
        {"nome": "Bordeaux (Médoc)", "territorio": "Francia", "vitigno": "Cabernet Sauvignon/Merlot",
         "profilo": "tannino strutturato, cassis, cedro, tabacco, note di grafite",
         "abbina": "agnello, manzo, selvaggina, formaggi stagionati",
         "perche": "il tannino del Cabernet sgrassa le carni rosse importanti"},
        {"nome": "Châteauneuf-du-Pape", "territorio": "Francia (Rodano)", "vitigno": "Grenache/Syrah",
         "profilo": "caldo, frutta scura, spezie, garrigue, alcol elevato",
         "abbina": "brasati, cacciagione, stufati speziati",
         "perche": "calore e struttura reggono cotture lunghe e piatti speziati"},
        {"nome": "Rioja Gran Reserva", "territorio": "Spagna", "vitigno": "Tempranillo",
         "profilo": "frutta matura, vaniglia, cuoio, lungo affinamento in rovere",
         "abbina": "agnello arrosto, tapas di carne, formaggi stagionati",
         "perche": "l'affinamento dona morbidezza che lega con arrosti e cotture ricche"},
        {"nome": "Malbec (Mendoza)", "territorio": "Argentina", "vitigno": "Malbec",
         "profilo": "frutta nera intensa, morbido, tannino vellutato, cacao",
         "abbina": "asado, bistecca, carne alla brace",
         "perche": "morbidezza e frutto sono perfetti sulla carne grigliata"},
        {"nome": "Cabernet Sauvignon (Napa)", "territorio": "USA (California)", "vitigno": "Cabernet Sauvignon",
         "profilo": "concentrato, frutta matura, cioccolato, rovere, corpo pieno",
         "abbina": "steak, hamburger gourmet, BBQ",
         "perche": "la concentrazione regge piatti americani grassi e affumicati"},
    ],
    "Rossi medi": [
        {"nome": "Pinot Noir (Borgogna)", "territorio": "Francia", "vitigno": "Pinot Noir",
         "profilo": "elegante, frutti rossi, sottobosco, tannino fine, acidità",
         "abbina": "anatra, funghi, salmone, carni bianche",
         "perche": "l'eleganza e l'acidità legano con piatti delicati e funghi"},
        {"nome": "Beaujolais", "territorio": "Francia", "vitigno": "Gamay",
         "profilo": "fruttato, fresco, tannino leggero, beverino",
         "abbina": "salumi, pollo, taglieri, piatti conviviali",
         "perche": "leggerezza e frutto per piatti informali e salumi"},
        {"nome": "Zinfandel", "territorio": "USA (California)", "vitigno": "Zinfandel",
         "profilo": "frutta matura, speziato, alcol generoso",
         "abbina": "BBQ, ribs, pizza saporita",
         "perche": "frutto dolce e alcol reggono salse barbecue affumicate"},
    ],
    "Bianchi freschi": [
        {"nome": "Sauvignon Blanc (Loira)", "territorio": "Francia", "vitigno": "Sauvignon Blanc",
         "profilo": "erbaceo, agrumi, minerale, acidità tagliente",
         "abbina": "crudi, capra fresca, asparagi, pesce",
         "perche": "l'acidità e le note verdi puliscono e legano con verdure ed erbe"},
        {"nome": "Albariño", "territorio": "Spagna (Rías Baixas)", "vitigno": "Albariño",
         "profilo": "salino, agrumi, pesca, acidità viva",
         "abbina": "frutti di mare, polpo, pesce alla griglia",
         "perche": "la salinità richiama il mare, l'acidità taglia il grasso del pesce"},
        {"nome": "Riesling secco (Mosella)", "territorio": "Germania", "vitigno": "Riesling",
         "profilo": "agrumi, mela verde, mineralità, acidità alta",
         "abbina": "cucina asiatica, pesce, piatti speziati",
         "perche": "l'acidità e la leggera dolcezza domano il piccante asiatico"},
        {"nome": "Grüner Veltliner", "territorio": "Austria", "vitigno": "Grüner Veltliner",
         "profilo": "pepato, agrumi, fresco, minerale",
         "abbina": "verdure, pesce, cucina viennese leggera",
         "perche": "la nota pepata lega con le verdure, l'acidità pulisce"},
    ],
    "Bianchi strutturati": [
        {"nome": "Chablis / Borgogna bianco", "territorio": "Francia", "vitigno": "Chardonnay",
         "profilo": "minerale, agrumi, burroso se in legno, corpo",
         "abbina": "ostriche, pesce in salsa, pollame cremoso",
         "perche": "la mineralità lega coi crostacei, il corpo regge le salse"},
        {"nome": "Viognier (Condrieu)", "territorio": "Francia (Rodano)", "vitigno": "Viognier",
         "profilo": "aromatico, albicocca, fiori, corpo pieno",
         "abbina": "pesce ricco, carni bianche speziate, cucina fusion",
         "perche": "l'aromaticità e il corpo reggono piatti profumati e speziati"},
    ],
    "Bollicine": [
        {"nome": "Champagne", "territorio": "Francia", "vitigno": "Chardonnay/Pinot Noir/Meunier",
         "profilo": "metodo classico, crosta di pane, agrumi, bollicina finissima, lunga sosta sui lieviti",
         "abbina": "aperitivo, ostriche, fritti, tutto il pasto",
         "perche": "acidità e bollicina finissima puliscono il palato meglio di ogni altro vino"},
        {"nome": "Cava", "territorio": "Spagna", "vitigno": "Macabeo/Xarel·lo/Parellada",
         "profilo": "metodo classico, fresco, agrumi, prezzo accessibile",
         "abbina": "aperitivo, tapas, fritture",
         "perche": "bollicina e freschezza per aperitivi e fritti, ottimo rapporto qualità-prezzo"},
        {"nome": "Crémant", "territorio": "Francia", "vitigno": "vari",
         "profilo": "metodo classico fuori Champagne, fresco, fine",
         "abbina": "aperitivo, pesce, antipasti",
         "perche": "alternativa allo Champagne, stessa pulizia del palato"},
    ],
    "Dolci e da meditazione": [
        {"nome": "Sauternes", "territorio": "Francia", "vitigno": "Sémillon (muffa nobile)",
         "profilo": "dolce, albicocca, miele, botrytis, acidità che bilancia",
         "abbina": "foie gras, formaggi erborinati, dolci alla frutta",
         "perche": "la dolcezza contrasta il sale del roquefort, l'acidità evita la stucchevolezza"},
        {"nome": "Porto", "territorio": "Portogallo", "vitigno": "vari (Douro)",
         "profilo": "fortificato dolce, frutta sotto spirito, cioccolato, alcol",
         "abbina": "cioccolato, formaggi blu, frutta secca",
         "perche": "il frutto dolce e l'alcol reggono il cioccolato fondente e i blu"},
        {"nome": "Tokaji", "territorio": "Ungheria", "vitigno": "Furmint (muffa nobile)",
         "profilo": "dolce, albicocca, miele, acidità viva, botrytis",
         "abbina": "dessert alla frutta, foie gras, formaggi erborinati",
         "perche": "acidità e dolcezza in equilibrio, storico vino da dessert"},
    ],
}

# unisci i vini del mondo nelle categorie della carta
for _cat, _lista in VINI_MONDO.items():
    if _cat in CARTA_VINI:
        CARTA_VINI[_cat]["vini"].extend(_lista)
