# mappa_italia_estesa.py
# ESPANSIONE della mappa piatti canonici italiani — piatti aggiuntivi per regione.
# Si somma a mappa_italia_regioni.py. Stesso schema: {nome, chiave, firma, disc?}.
# Fonte: tradizione regionale codificata. Verificabile da un professionista italiano.

REGIONI_ESTESE = {
    "Lazio": [
        {"nome": "Bucatini all'arrabbiata", "chiave": "pomodoro", "firma": ["bucatini", "pomodoro", "aglio", "peperoncino", "olio"]},
        {"nome": "Pasta e ceci alla romana", "chiave": "ceci", "firma": ["pasta", "ceci", "rosmarino", "aglio", "olio"]},
        {"nome": "Coratella con carciofi", "chiave": "coratella", "firma": ["coratella d'agnello", "carciofi", "vino bianco"]},
        {"nome": "Puntarelle alla romana", "chiave": "puntarelle", "firma": ["puntarelle", "acciughe", "aglio", "aceto", "olio"]},
        {"nome": "Supplì", "chiave": "riso", "firma": ["riso", "ragù", "mozzarella", "pangrattato"]},
        {"nome": "Fettuccine alla papalina", "chiave": "uova", "firma": ["fettuccine", "prosciutto", "piselli", "uova", "parmigiano"]},
        {"nome": "Pollo alla romana coi peperoni", "chiave": "pollo", "firma": ["pollo", "peperoni", "pomodoro", "vino bianco"]},
        {"nome": "Coda alla vaccinara", "chiave": "coda di bue", "firma": ["coda di bue", "sedano", "pomodoro", "pinoli", "uvetta"]},
        {"nome": "Filetti di baccalà fritti", "chiave": "baccalà", "firma": ["baccalà", "pastella", "olio per friggere"]},
        {"nome": "Crostata di ricotta e visciole", "chiave": "ricotta", "firma": ["pasta frolla", "ricotta", "visciole"], "disc": "pasticceria"},
    ],
    "Campania": [
        {"nome": "Spaghetti alla puttanesca", "chiave": "pomodoro", "firma": ["spaghetti", "pomodoro", "olive", "capperi", "acciughe", "aglio"]},
        {"nome": "Linguine agli scampi", "chiave": "scampi", "firma": ["linguine", "scampi", "aglio", "pomodorini", "prezzemolo"]},
        {"nome": "Impepata di cozze", "chiave": "cozze", "firma": ["cozze", "pepe", "prezzemolo", "limone"]},
        {"nome": "Polpo alla luciana", "chiave": "polpo", "firma": ["polpo", "pomodorini", "olive", "capperi", "peperoncino"]},
        {"nome": "Pasta e patate con provola", "chiave": "patate", "firma": ["pasta mista", "patate", "provola", "sedano"]},
        {"nome": "Friarielli e salsiccia", "chiave": "friarielli", "firma": ["friarielli", "salsiccia", "aglio", "peperoncino"]},
        {"nome": "Zuppa di soffritto", "chiave": "frattaglie", "firma": ["frattaglie di maiale", "peperoncino", "pomodoro"]},
        {"nome": "Migliaccio", "chiave": "semola", "firma": ["semola", "ricotta", "uova", "acqua di fiori d'arancio"], "disc": "pasticceria"},
        {"nome": "Delizia al limone", "chiave": "limone", "firma": ["pan di spagna", "limone", "crema", "panna"], "disc": "pasticceria"},
        {"nome": "Struffoli", "chiave": "farina", "firma": ["farina", "uova", "miele", "confettini"], "disc": "pasticceria"},
        {"nome": "Zeppole di San Giuseppe", "chiave": "farina", "firma": ["pasta choux", "crema pasticcera", "amarena"], "disc": "pasticceria"},
    ],
    "Sicilia": [
        {"nome": "Pasta 'ncasciata", "chiave": "melanzane", "firma": ["pasta", "melanzane", "ragù", "caciocavallo", "uova sode"]},
        {"nome": "Involtini di pesce spada", "chiave": "pesce spada", "firma": ["pesce spada", "pangrattato", "pinoli", "uvetta"]},
        {"nome": "Couscous alla trapanese", "chiave": "pesce", "firma": ["couscous", "pesce misto", "brodo", "mandorle"]},
        {"nome": "Pesce spada alla ghiotta", "chiave": "pesce spada", "firma": ["pesce spada", "pomodoro", "olive", "capperi", "sedano"]},
        {"nome": "Falsomagro", "chiave": "manzo", "firma": ["fettina di manzo", "uova sode", "salame", "formaggio"]},
        {"nome": "Panelle", "chiave": "ceci", "firma": ["farina di ceci", "acqua", "prezzemolo", "olio per friggere"]},
        {"nome": "Arancini al ragù", "chiave": "riso", "firma": ["riso", "ragù", "piselli", "caciocavallo", "pangrattato"]},
        {"nome": "Caponata di melanzane", "chiave": "melanzane", "firma": ["melanzane", "sedano", "olive", "capperi", "aceto"]},
        {"nome": "Iris fritta", "chiave": "ricotta", "firma": ["pasta brioche", "ricotta", "gocce di cioccolato"], "disc": "pasticceria"},
        {"nome": "Frutta martorana", "chiave": "mandorle", "firma": ["pasta di mandorle", "zucchero"], "disc": "pasticceria"},
        {"nome": "Gelo di melone", "chiave": "anguria", "firma": ["anguria", "amido", "zucchero", "gelsomino"], "disc": "pasticceria"},
        {"nome": "Brioche col tuppo", "chiave": "farina", "firma": ["farina", "uova", "burro", "zucchero"], "disc": "panificazione"},
    ],
    "Lombardia": [
        {"nome": "Risotto al salto", "chiave": "riso carnaroli", "firma": ["risotto alla milanese", "burro"]},
        {"nome": "Casoncelli alla bergamasca", "chiave": "carne", "firma": ["pasta", "ripieno di carne", "burro", "salvia", "pancetta"]},
        {"nome": "Rostin negaa", "chiave": "vitello", "firma": ["nodini di vitello", "vino bianco", "salvia", "burro"]},
        {"nome": "Polenta e bruscitt", "chiave": "manzo", "firma": ["manzo", "vino", "polenta"]},
        {"nome": "Mondeghili", "chiave": "carne", "firma": ["carne lessa", "pane", "uova", "pangrattato"]},
        {"nome": "Sbrisolona", "chiave": "mandorle", "firma": ["farina", "farina di mais", "mandorle", "burro"], "disc": "pasticceria"},
        {"nome": "Torta paradiso", "chiave": "farina", "firma": ["farina", "fecola", "burro", "uova", "zucchero"], "disc": "pasticceria"},
    ],
    "Emilia-Romagna": [
        {"nome": "Cappelletti in brodo", "chiave": "carne", "firma": ["pasta all'uovo", "ripieno", "brodo di cappone"]},
        {"nome": "Passatelli in brodo", "chiave": "pane", "firma": ["pangrattato", "parmigiano", "uova", "brodo"]},
        {"nome": "Gramigna con salsiccia", "chiave": "salsiccia", "firma": ["gramigna", "salsiccia", "panna", "pomodoro"]},
        {"nome": "Cotoletta alla bolognese", "chiave": "vitello", "firma": ["vitello", "prosciutto", "parmigiano", "brodo"]},
        {"nome": "Erbazzone", "chiave": "bietole", "firma": ["bietole", "parmigiano", "pancetta", "pasta"]},
        {"nome": "Zuppa inglese", "chiave": "uova", "firma": ["savoiardi", "crema", "alchermes"], "disc": "pasticceria"},
        {"nome": "Torta di riso", "chiave": "riso", "firma": ["riso", "latte", "uova", "mandorle", "liquore"], "disc": "pasticceria"},
    ],
    "Toscana": [
        {"nome": "Pici all'aglione", "chiave": "aglio", "firma": ["pici", "aglione", "pomodoro", "olio"]},
        {"nome": "Crostini di fegatini", "chiave": "fegatini", "firma": ["pane", "fegatini di pollo", "capperi", "acciughe"]},
        {"nome": "Cacciucco", "chiave": "pesce", "firma": ["pesce misto", "pomodoro", "vino rosso", "peperoncino", "pane"]},
        {"nome": "Peposo", "chiave": "manzo", "firma": ["manzo", "pepe nero", "vino rosso", "aglio"]},
        {"nome": "Trippa alla fiorentina", "chiave": "trippa", "firma": ["trippa", "pomodoro", "parmigiano"]},
        {"nome": "Arista di maiale", "chiave": "maiale", "firma": ["lombo di maiale", "rosmarino", "aglio", "finocchietto"]},
        {"nome": "Castagnaccio", "chiave": "farina di castagne", "firma": ["farina di castagne", "pinoli", "rosmarino", "uvetta"], "disc": "pasticceria"},
        {"nome": "Schiacciata all'uva", "chiave": "uva", "firma": ["pasta pane", "uva", "zucchero"], "disc": "panificazione"},
    ],
    "Piemonte": [
        {"nome": "Vitello tonnato", "chiave": "vitello", "firma": ["vitello", "tonno", "acciughe", "capperi", "maionese"]},
        {"nome": "Tajarin al ragù", "chiave": "carne macinata", "firma": ["tajarin", "ragù", "burro"]},
        {"nome": "Risotto al Barolo", "chiave": "riso carnaroli", "firma": ["riso", "vino barolo", "brodo", "burro"]},
        {"nome": "Fritto misto alla piemontese", "chiave": "carne", "firma": ["carni miste", "semolino dolce", "amaretti", "pangrattato"]},
        {"nome": "Finanziera", "chiave": "frattaglie", "firma": ["frattaglie", "creste di gallo", "marsala", "aceto"]},
        {"nome": "Panna cotta", "chiave": "panna", "firma": ["panna", "zucchero", "gelatina", "vaniglia"], "disc": "pasticceria"},
        {"nome": "Bonet", "chiave": "uova", "firma": ["uova", "cacao", "amaretti", "latte", "rum"], "disc": "pasticceria"},
        {"nome": "Gianduiotto", "chiave": "cioccolato", "firma": ["cioccolato", "nocciole", "zucchero"], "disc": "pasticceria"},
    ],
    "Veneto": [
        {"nome": "Bigoli in salsa", "chiave": "acciughe", "firma": ["bigoli", "acciughe", "cipolla", "olio"]},
        {"nome": "Risotto al nero di seppia", "chiave": "seppia", "firma": ["riso", "seppie", "nero di seppia", "brodo"]},
        {"nome": "Pasta e fagioli alla veneta", "chiave": "fagioli", "firma": ["pasta", "fagioli borlotti", "cotenna", "rosmarino"]},
        {"nome": "Sarde in saor", "chiave": "sarde", "firma": ["sarde", "cipolla", "aceto", "uvetta", "pinoli"]},
        {"nome": "Polenta e schie", "chiave": "gamberetti", "firma": ["polenta", "schie", "aglio", "prezzemolo"]},
        {"nome": "Radicchio di Treviso alla griglia", "chiave": "radicchio", "firma": ["radicchio di treviso", "olio", "sale"]},
        {"nome": "Pandoro", "chiave": "farina", "firma": ["farina", "burro", "uova", "lievito madre", "vaniglia"], "disc": "panificazione"},
        {"nome": "Frittelle veneziane", "chiave": "farina", "firma": ["farina", "uvetta", "pinoli", "grappa"], "disc": "pasticceria"},
    ],
    "Puglia": [
        {"nome": "Orecchiette al pomodoro e cacioricotta", "chiave": "pomodoro", "firma": ["orecchiette", "pomodoro", "cacioricotta", "basilico"]},
        {"nome": "Ciceri e tria", "chiave": "ceci", "firma": ["pasta", "ceci", "aglio", "alloro"]},
        {"nome": "Riso patate e cozze (tiella)", "chiave": "cozze", "firma": ["riso", "patate", "cozze", "pomodoro", "pecorino"]},
        {"nome": "Braciole al sugo", "chiave": "manzo", "firma": ["fettine di manzo", "pecorino", "aglio", "pomodoro"]},
        {"nome": "Panzerotti fritti", "chiave": "farina", "firma": ["pasta pane", "pomodoro", "mozzarella"], "disc": "panificazione"},
        {"nome": "Pasticciotto leccese", "chiave": "crema", "firma": ["pasta frolla", "crema pasticcera", "amarena"], "disc": "pasticceria"},
        {"nome": "Cartellate", "chiave": "farina", "firma": ["farina", "vino", "vincotto o miele"], "disc": "pasticceria"},
    ],
    "Liguria": [
        {"nome": "Pansoti con salsa di noci", "chiave": "noci", "firma": ["pansoti", "preboggion", "ricotta", "salsa di noci"]},
        {"nome": "Cima alla genovese", "chiave": "vitello", "firma": ["pancia di vitello", "uova", "piselli", "pistacchi"]},
        {"nome": "Coniglio alla ligure", "chiave": "coniglio", "firma": ["coniglio", "olive taggiasche", "pinoli", "vino"]},
        {"nome": "Torta pasqualina", "chiave": "bietole", "firma": ["pasta sfoglia", "bietole", "ricotta", "uova"]},
        {"nome": "Acciughe ripiene", "chiave": "acciughe", "firma": ["acciughe", "pangrattato", "parmigiano", "uova"]},
        {"nome": "Pandolce genovese", "chiave": "farina", "firma": ["farina", "uvetta", "pinoli", "canditi", "finocchietto"], "disc": "pasticceria"},
    ],
    "Sardegna": [
        {"nome": "Malloreddus alla campidanese", "chiave": "salsiccia", "firma": ["malloreddus", "salsiccia", "pomodoro", "zafferano", "pecorino"]},
        {"nome": "Pane frattau", "chiave": "pane carasau", "firma": ["pane carasau", "pomodoro", "uovo", "pecorino"]},
        {"nome": "Zuppa gallurese", "chiave": "pane", "firma": ["pane", "formaggio", "brodo"]},
        {"nome": "Bottarga di muggine", "chiave": "bottarga", "firma": ["bottarga", "spaghetti", "olio", "limone"]},
        {"nome": "Agnello con finocchietti", "chiave": "agnello", "firma": ["agnello", "finocchietto selvatico", "uova"]},
        {"nome": "Pardulas", "chiave": "ricotta", "firma": ["semola", "ricotta", "zafferano", "scorza d'arancia"], "disc": "pasticceria"},
        {"nome": "Pane carasau", "chiave": "semola", "firma": ["semola", "acqua", "lievito", "sale"], "disc": "panificazione"},
    ],
    "Calabria": [
        {"nome": "Fileja con 'nduja", "chiave": "nduja", "firma": ["fileja", "nduja", "pomodoro", "cipolla"]},
        {"nome": "Pasta ca muddica", "chiave": "acciughe", "firma": ["pasta", "acciughe", "mollica di pane", "aglio"]},
        {"nome": "Sardella (rosamarina)", "chiave": "sarde", "firma": ["novellame di sarde", "peperoncino", "sale"]},
        {"nome": "Melanzane alla parmigiana calabrese", "chiave": "melanzane", "firma": ["melanzane", "pomodoro", "provola", "uova"]},
        {"nome": "Pignolata glassata", "chiave": "farina", "firma": ["farina", "uova", "miele o glassa"], "disc": "pasticceria"},
        {"nome": "Cuzzupa", "chiave": "farina", "firma": ["farina", "uova", "strutto"], "disc": "pasticceria"},
    ],
    "Abruzzo": [
        {"nome": "Spaghetti alla chitarra al ragù", "chiave": "carne", "firma": ["pasta alla chitarra", "ragù misto", "peperoncino"]},
        {"nome": "Pallotte cacio e ova", "chiave": "formaggio", "firma": ["pane", "pecorino", "uova", "pomodoro"]},
        {"nome": "Agnello cacio e uova", "chiave": "agnello", "firma": ["agnello", "uova", "pecorino", "limone"]},
        {"nome": "Scrippelle 'mbusse", "chiave": "uova", "firma": ["crespelle", "pecorino", "brodo"]},
        {"nome": "Parrozzo", "chiave": "mandorle", "firma": ["semolino", "mandorle", "cioccolato"], "disc": "pasticceria"},
        {"nome": "Ferratelle", "chiave": "farina", "firma": ["farina", "uova", "olio", "zucchero"], "disc": "pasticceria"},
    ],
    "Marche": [
        {"nome": "Passatelli in brodo", "chiave": "pane", "firma": ["pangrattato", "parmigiano", "uova", "brodo"]},
        {"nome": "Coniglio in porchetta", "chiave": "coniglio", "firma": ["coniglio", "finocchietto", "aglio", "pancetta"]},
        {"nome": "Stoccafisso all'anconetana", "chiave": "stoccafisso", "firma": ["stoccafisso", "patate", "pomodoro", "olive"]},
        {"nome": "Ciauscolo su pane", "chiave": "maiale", "firma": ["salame ciauscolo", "pane"]},
        {"nome": "Frustingo", "chiave": "fichi", "firma": ["fichi secchi", "noci", "mandorle", "cacao"], "disc": "pasticceria"},
    ],
    "Umbria": [
        {"nome": "Strangozzi alla spoletina", "chiave": "pomodoro", "firma": ["strangozzi", "pomodoro", "aglio", "peperoncino"]},
        {"nome": "Palombacce alla ghiotta", "chiave": "piccione", "firma": ["colombacci", "olive", "vino", "salvia"]},
        {"nome": "Salsiccia e lenticchie", "chiave": "lenticchie", "firma": ["lenticchie di castelluccio", "salsiccia", "soffritto"]},
        {"nome": "Imbrecciata", "chiave": "legumi", "firma": ["legumi misti", "farro", "verdure"]},
        {"nome": "Rocciata", "chiave": "mele", "firma": ["pasta", "mele", "noci", "uvetta"], "disc": "pasticceria"},
    ],
    "Trentino-Alto Adige": [
        {"nome": "Canederli in brodo", "chiave": "pane", "firma": ["pane raffermo", "speck", "uova", "latte", "brodo"]},
        {"nome": "Spätzle agli spinaci", "chiave": "farina", "firma": ["farina", "spinaci", "uova", "burro"]},
        {"nome": "Schlutzkrapfen", "chiave": "spinaci", "firma": ["pasta", "spinaci", "ricotta", "burro"]},
        {"nome": "Stinco di maiale al forno", "chiave": "maiale", "firma": ["stinco di maiale", "birra", "cumino"]},
        {"nome": "Zelten", "chiave": "frutta secca", "firma": ["fichi", "noci", "mandorle", "uvetta"], "disc": "pasticceria"},
        {"nome": "Krapfen", "chiave": "farina", "firma": ["farina", "uova", "marmellata"], "disc": "pasticceria"},
    ],
    "Friuli-Venezia Giulia": [
        {"nome": "Frico con patate", "chiave": "formaggio montasio", "firma": ["montasio", "patate", "cipolla"]},
        {"nome": "Cjarsons carnici", "chiave": "patate", "firma": ["pasta", "patate", "erbe", "uvetta", "ricotta affumicata"]},
        {"nome": "Brovada e muset", "chiave": "maiale", "firma": ["cotechino (muset)", "rape (brovada)"]},
        {"nome": "Gulasch triestino", "chiave": "manzo", "firma": ["manzo", "cipolla", "paprika", "pomodoro"]},
        {"nome": "Gubana", "chiave": "frutta secca", "firma": ["pasta lievitata", "noci", "uvetta", "grappa"], "disc": "pasticceria"},
        {"nome": "Presnitz", "chiave": "frutta secca", "firma": ["pasta sfoglia", "noci", "uvetta", "pinoli"], "disc": "pasticceria"},
    ],
    "Basilicata": [
        {"nome": "Strascinati con peperoni cruschi", "chiave": "peperoni", "firma": ["strascinati", "peperoni cruschi", "mollica", "aglio"]},
        {"nome": "Ciaudedda", "chiave": "carciofi", "firma": ["carciofi", "fave", "patate", "pancetta"]},
        {"nome": "Agnello alla lucana", "chiave": "agnello", "firma": ["agnello", "patate", "peperoni", "pecorino"]},
        {"nome": "Rafanata", "chiave": "rafano", "firma": ["rafano", "uova", "pecorino", "patate"]},
        {"nome": "Taralli lucani", "chiave": "farina", "firma": ["farina", "vino bianco", "olio", "semi di finocchio"], "disc": "panificazione"},
    ],
    "Molise": [
        {"nome": "Cavatelli con ragù di castrato", "chiave": "castrato", "firma": ["cavatelli", "castrato", "pomodoro"]},
        {"nome": "Pampanella di San Martino", "chiave": "maiale", "firma": ["maiale", "peperoncino dolce", "aceto", "aglio"]},
        {"nome": "Brodetto di pesce alla termolese", "chiave": "pesce", "firma": ["pesce misto", "pomodoro", "peperoncino"]},
        {"nome": "Fusilli con la ventricina", "chiave": "ventricina", "firma": ["fusilli", "ventricina", "pomodoro"]},
        {"nome": "Calcioni", "chiave": "formaggio", "firma": ["pasta", "ricotta", "provola", "uova"], "disc": "pasticceria"},
    ],
    "Valle d'Aosta": [
        {"nome": "Fonduta valdostana", "chiave": "fontina", "firma": ["fontina", "latte", "tuorli", "burro"]},
        {"nome": "Zuppa alla valpellinentze", "chiave": "cavolo", "firma": ["cavolo", "pane", "fontina", "brodo"]},
        {"nome": "Polenta concia", "chiave": "farina di mais", "firma": ["farina di mais", "fontina", "burro"]},
        {"nome": "Carbonada valdostana", "chiave": "manzo", "firma": ["manzo", "vino rosso", "cipolla", "spezie"]},
        {"nome": "Tegole valdostane", "chiave": "nocciole", "firma": ["nocciole", "mandorle", "zucchero", "burro"], "disc": "pasticceria"},
    ],
}
