# mappa_mondo3.py
# MAPPA MONDO — parte 3: espansione delle cucine principali + nuove cucine.

CUCINE3 = {
    "Giappone": [
        {"nome": "Sashimi", "chiave": "pesce", "firma": ["pesce crudo", "wasabi", "salsa di soia"]},
        {"nome": "Yakitori", "chiave": "pollo", "firma": ["pollo", "salsa tare", "cipollotto"]},
        {"nome": "Sukiyaki", "chiave": "manzo", "firma": ["manzo", "salsa di soia", "verdure", "tofu", "uovo"]},
        {"nome": "Shabu shabu", "chiave": "manzo", "firma": ["manzo", "brodo dashi", "verdure", "salse"]},
        {"nome": "Takoyaki", "chiave": "polpo", "firma": ["pastella", "polpo", "salsa takoyaki", "katsuobushi"]},
        {"nome": "Curry giapponese", "chiave": "manzo", "firma": ["carne", "patate", "carote", "roux di curry", "riso"]},
        {"nome": "Karaage", "chiave": "pollo", "firma": ["pollo", "salsa di soia", "zenzero", "fecola", "olio"]},
        {"nome": "Ramen miso", "chiave": "miso", "firma": ["noodles", "brodo miso", "mais", "burro", "chashu"]},
        {"nome": "Dorayaki", "chiave": "farina", "firma": ["pancake", "anko"], "disc": "pasticceria"},
    ],
    "Cina": [
        {"nome": "Dim sum har gow", "chiave": "gamberi", "firma": ["pasta di amido", "gamberi", "germogli di bambù"]},
        {"nome": "Pollo del generale Tso", "chiave": "pollo", "firma": ["pollo fritto", "salsa agrodolce", "peperoncino"]},
        {"nome": "Manzo alla sichuan", "chiave": "manzo", "firma": ["manzo", "pepe di sichuan", "peperoncino", "sedano"]},
        {"nome": "Zuppa acida e piccante", "chiave": "tofu", "firma": ["tofu", "funghi", "aceto", "pepe bianco", "uovo"]},
        {"nome": "Riso fritto Yangzhou", "chiave": "riso", "firma": ["riso", "gamberi", "prosciutto", "uova", "piselli"]},
        {"nome": "Spaghetti dan dan", "chiave": "noodles", "firma": ["noodles", "maiale", "pasta di sesamo", "pepe di sichuan"]},
        {"nome": "Pollo gong bao", "chiave": "pollo", "firma": ["pollo", "arachidi", "peperoncino", "pepe di sichuan"]},
        {"nome": "Melanzane alla sichuan", "chiave": "melanzane", "firma": ["melanzane", "aglio", "doubanjiang", "salsa di soia"]},
    ],
    "India": [
        {"nome": "Vindaloo", "chiave": "maiale", "firma": ["maiale", "aceto", "peperoncino", "aglio", "spezie"]},
        {"nome": "Korma", "chiave": "pollo", "firma": ["pollo", "yogurt", "mandorle", "panna", "spezie dolci"]},
        {"nome": "Saag paneer", "chiave": "paneer", "firma": ["spinaci", "senape", "paneer", "spezie"]},
        {"nome": "Butter naan", "chiave": "farina", "firma": ["farina", "burro", "yogurt", "aglio"], "disc": "panificazione"},
        {"nome": "Pakora", "chiave": "ceci", "firma": ["farina di ceci", "verdure", "spezie", "olio"]},
        {"nome": "Raita", "chiave": "yogurt", "firma": ["yogurt", "cetriolo", "cumino", "menta"]},
        {"nome": "Idli", "chiave": "riso", "firma": ["riso fermentato", "lenticchie urad", "cottura a vapore"]},
        {"nome": "Gulab jamun", "chiave": "latte", "firma": ["latte in polvere", "sciroppo di zucchero", "cardamomo"], "disc": "pasticceria"},
    ],
    "Francia": [
        {"nome": "Blanquette de veau", "chiave": "vitello", "firma": ["vitello", "panna", "funghi", "cipolline"]},
        {"nome": "Cassoulet toulousain", "chiave": "fagioli", "firma": ["fagioli", "salsiccia", "confit d'anatra"]},
        {"nome": "Pot-au-feu", "chiave": "manzo", "firma": ["manzo", "verdure", "brodo", "midollo"]},
        {"nome": "Gratin dauphinois", "chiave": "patate", "firma": ["patate", "panna", "aglio", "gruyère"]},
        {"nome": "Salade niçoise", "chiave": "tonno", "firma": ["tonno", "acciughe", "olive", "fagiolini", "uova"]},
        {"nome": "Escargots alla bourguignonne", "chiave": "lumache", "firma": ["lumache", "burro all'aglio", "prezzemolo"]},
        {"nome": "Moules marinières", "chiave": "cozze", "firma": ["cozze", "vino bianco", "scalogno", "prezzemolo"]},
        {"nome": "Éclair", "chiave": "farina", "firma": ["pasta choux", "crema pasticcera", "glassa"], "disc": "pasticceria"},
        {"nome": "Mille-feuille", "chiave": "farina", "firma": ["pasta sfoglia", "crema pasticcera"], "disc": "pasticceria"},
        {"nome": "Madeleine", "chiave": "farina", "firma": ["farina", "burro", "uova", "limone"], "disc": "pasticceria"},
        {"nome": "Profiteroles", "chiave": "farina", "firma": ["pasta choux", "panna", "cioccolato"], "disc": "pasticceria"},
    ],
    "Messico": [
        {"nome": "Chilaquiles", "chiave": "tortilla", "firma": ["tortilla", "salsa", "formaggio", "uova"]},
        {"nome": "Tostadas", "chiave": "tortilla", "firma": ["tortilla croccante", "fagioli", "carne", "lattuga"]},
        {"nome": "Sopa de tortilla", "chiave": "tortilla", "firma": ["brodo", "tortilla", "pomodoro", "avocado"]},
        {"nome": "Cochinita pibil", "chiave": "maiale", "firma": ["maiale", "achiote", "arancia amara", "foglia di banano"]},
        {"nome": "Tacos de pescado", "chiave": "pesce", "firma": ["tortilla", "pesce", "cavolo", "salsa"]},
        {"nome": "Fajitas", "chiave": "manzo", "firma": ["manzo", "peperoni", "cipolla", "tortilla"]},
    ],
    "Corea": [
        {"nome": "Galbi", "chiave": "manzo", "firma": ["costine di manzo", "salsa di soia", "pera", "aglio"]},
        {"nome": "Haemul pajeon", "chiave": "frutti di mare", "firma": ["pastella", "cipollotto", "frutti di mare"]},
        {"nome": "Doenjang jjigae", "chiave": "pasta di soia", "firma": ["doenjang", "tofu", "zucchine", "vongole"]},
        {"nome": "Naengmyeon", "chiave": "noodles", "firma": ["noodles di grano saraceno", "brodo freddo", "uovo", "cetriolo"]},
    ],
    "Portogallo": [
        {"nome": "Bacalhau à brás", "chiave": "baccalà", "firma": ["baccalà", "patate", "uova", "cipolla"]},
        {"nome": "Caldo verde", "chiave": "cavolo", "firma": ["cavolo", "patate", "chorizo", "olio"]},
        {"nome": "Bifana", "chiave": "maiale", "firma": ["maiale", "aglio", "vino bianco", "pane"]},
        {"nome": "Pastel de nata", "chiave": "crema", "firma": ["pasta sfoglia", "crema all'uovo", "cannella"], "disc": "pasticceria"},
        {"nome": "Cataplana di frutti di mare", "chiave": "frutti di mare", "firma": ["vongole", "gamberi", "pomodoro", "coriandolo"]},
    ],
    "Turchia": [
        {"nome": "Kebab adana", "chiave": "agnello", "firma": ["agnello macinato", "peperoncino", "spiedino"]},
        {"nome": "Menemen", "chiave": "uova", "firma": ["uova", "pomodoro", "peperoni", "peperoncino"]},
        {"nome": "Dolma", "chiave": "riso", "firma": ["foglie di vite", "riso", "pinoli", "erbe"]},
        {"nome": "Lahmacun", "chiave": "carne macinata", "firma": ["pasta sottile", "carne macinata", "pomodoro", "spezie"], "disc": "panificazione"},
        {"nome": "Köfte", "chiave": "carne macinata", "firma": ["carne macinata", "cipolla", "spezie", "prezzemolo"]},
        {"nome": "Baklava turca", "chiave": "frutta secca", "firma": ["pasta fillo", "pistacchi", "sciroppo"], "disc": "pasticceria"},
    ],
    "Libano": [
        {"nome": "Kibbeh", "chiave": "carne macinata", "firma": ["bulgur", "carne macinata", "cipolla", "spezie"]},
        {"nome": "Manakish", "chiave": "farina", "firma": ["pasta", "za'atar", "olio"], "disc": "panificazione"},
        {"nome": "Fattoush libanese", "chiave": "verdure", "firma": ["pane pita", "verdure", "sumac", "melassa di melograno"]},
        {"nome": "Warak enab", "chiave": "riso", "firma": ["foglie di vite", "riso", "carne", "limone"]},
    ],
}
