# mappa_mondo.py
# MAPPA DEI PIATTI CANONICI DEL MONDO per cucina nazionale.
# Stesso schema: {nome, chiave, firma, disc?}. Piatti canonici veri, verificati.
# Molti agganciano i FENOMENI DEL MONDO già nel grafo (nixtamalizzazione, wok hei, koji, tandoor, ecc.).

CUCINE = {
    "Giappone": [
        {"nome": "Ramen tonkotsu", "chiave": "ossa di maiale", "firma": ["noodles kansui", "brodo di ossa di maiale", "chashu", "salsa di soia"]},
        {"nome": "Ramen shoyu", "chiave": "salsa di soia", "firma": ["noodles", "brodo dashi", "salsa di soia", "chashu"]},
        {"nome": "Sushi nigiri", "chiave": "riso", "firma": ["riso per sushi", "aceto di riso", "pesce crudo"]},
        {"nome": "Maki roll", "chiave": "riso", "firma": ["riso per sushi", "alga nori", "pesce", "verdure"]},
        {"nome": "Tempura", "chiave": "gamberi", "firma": ["gamberi", "verdure", "pastella", "olio per friggere"]},
        {"nome": "Tonkatsu", "chiave": "maiale", "firma": ["lonza di maiale", "panko", "uova", "salsa tonkatsu"]},
        {"nome": "Gyoza", "chiave": "maiale", "firma": ["pasta", "maiale macinato", "cavolo", "zenzero"]},
        {"nome": "Miso soup", "chiave": "miso", "firma": ["dashi", "miso", "tofu", "alga wakame"]},
        {"nome": "Teriyaki di pollo", "chiave": "pollo", "firma": ["pollo", "salsa di soia", "mirin", "zucchero"]},
        {"nome": "Okonomiyaki", "chiave": "cavolo", "firma": ["farina", "cavolo", "uova", "salsa okonomiyaki"]},
        {"nome": "Katsudon", "chiave": "maiale", "firma": ["tonkatsu", "uova", "cipolla", "riso"]},
        {"nome": "Udon in brodo", "chiave": "udon", "firma": ["udon", "dashi", "salsa di soia", "cipollotto"]},
        {"nome": "Onigiri", "chiave": "riso", "firma": ["riso", "alga nori", "ripieno (umeboshi/salmone)"]},
        {"nome": "Chawanmushi", "chiave": "uova", "firma": ["uova", "dashi", "gamberi", "funghi"]},
        {"nome": "Mochi", "chiave": "riso glutinoso", "firma": ["riso glutinoso", "zucchero", "ripieno anko"], "disc": "pasticceria"},
    ],
    "Cina": [
        {"nome": "Mapo tofu", "chiave": "tofu", "firma": ["tofu", "carne macinata", "doubanjiang", "pepe di sichuan"]},
        {"nome": "Kung pao chicken", "chiave": "pollo", "firma": ["pollo", "arachidi", "peperoncino secco", "salsa di soia"]},
        {"nome": "Anatra alla pechinese", "chiave": "anatra", "firma": ["anatra", "salsa hoisin", "cipollotto", "pancake"]},
        {"nome": "Maiale in agrodolce", "chiave": "maiale", "firma": ["maiale", "ananas", "peperoni", "salsa agrodolce"]},
        {"nome": "Chow mein", "chiave": "noodles", "firma": ["noodles", "verdure", "salsa di soia", "germogli"]},
        {"nome": "Riso alla cantonese", "chiave": "riso", "firma": ["riso", "uova", "prosciutto", "piselli", "gamberetti"]},
        {"nome": "Jiaozi (ravioli)", "chiave": "maiale", "firma": ["pasta", "maiale", "cavolo cinese", "zenzero"]},
        {"nome": "Xiao long bao", "chiave": "maiale", "firma": ["pasta", "maiale", "brodo in gelatina"]},
        {"nome": "Char siu", "chiave": "maiale", "firma": ["maiale", "salsa hoisin", "miele", "cinque spezie"]},
        {"nome": "Baozi al vapore", "chiave": "farina", "firma": ["pasta lievitata", "ripieno di maiale"], "disc": "panificazione"},
        {"nome": "Manzo con broccoli", "chiave": "manzo", "firma": ["manzo", "broccoli", "salsa di ostriche", "aglio"]},
        {"nome": "Gamberi kung pao", "chiave": "gamberi", "firma": ["gamberi", "arachidi", "peperoncino", "salsa"]},
        {"nome": "Wonton in brodo", "chiave": "gamberi", "firma": ["pasta wonton", "gamberi", "maiale", "brodo"]},
    ],
    "Corea": [
        {"nome": "Bibimbap", "chiave": "riso", "firma": ["riso", "verdure", "manzo", "uovo", "gochujang"]},
        {"nome": "Bulgogi", "chiave": "manzo", "firma": ["manzo", "salsa di soia", "zucchero", "aglio", "pera"]},
        {"nome": "Kimchi jjigae", "chiave": "kimchi", "firma": ["kimchi", "maiale", "tofu", "gochugaru"]},
        {"nome": "Japchae", "chiave": "noodles di patata dolce", "firma": ["noodles di patata dolce", "verdure", "manzo", "salsa di soia"]},
        {"nome": "Tteokbokki", "chiave": "tteok", "firma": ["tteok", "gochujang", "cipollotto", "uova sode"]},
        {"nome": "Korean fried chicken", "chiave": "pollo", "firma": ["pollo", "doppia frittura", "salsa gochujang"]},
        {"nome": "Samgyeopsal", "chiave": "maiale", "firma": ["pancetta di maiale", "aglio", "ssamjang", "lattuga"]},
        {"nome": "Sundubu jjigae", "chiave": "tofu", "firma": ["tofu morbido", "frutti di mare", "gochugaru", "uovo"]},
        {"nome": "Kimchi", "chiave": "cavolo", "firma": ["cavolo cinese", "gochugaru", "aglio", "zenzero", "salsa di pesce"]},
    ],
    "Messico": [
        {"nome": "Tacos al pastor", "chiave": "maiale", "firma": ["tortilla di mais", "maiale marinato", "ananas", "coriandolo", "cipolla"]},
        {"nome": "Tacos de carnitas", "chiave": "maiale", "firma": ["tortilla di mais", "maiale confit", "coriandolo", "cipolla"]},
        {"nome": "Guacamole", "chiave": "avocado", "firma": ["avocado", "lime", "coriandolo", "cipolla", "peperoncino"]},
        {"nome": "Enchiladas", "chiave": "tortilla", "firma": ["tortilla di mais", "salsa", "formaggio", "pollo"]},
        {"nome": "Quesadillas", "chiave": "formaggio", "firma": ["tortilla", "formaggio", "peperoncino"]},
        {"nome": "Pozole rosso", "chiave": "mais", "firma": ["hominy (mais nixtamalizzato)", "maiale", "peperoncino", "origano"]},
        {"nome": "Mole poblano", "chiave": "cioccolato", "firma": ["pollo", "peperoncini", "cioccolato", "spezie"]},
        {"nome": "Chiles en nogada", "chiave": "peperoni", "firma": ["peperoni poblano", "picadillo", "salsa di noci", "melograno"]},
        {"nome": "Tamales", "chiave": "masa", "firma": ["masa", "ripieno", "foglie di mais"]},
        {"nome": "Ceviche", "chiave": "pesce", "firma": ["pesce crudo", "lime", "coriandolo", "cipolla", "peperoncino"]},
        {"nome": "Elote", "chiave": "mais", "firma": ["mais", "maionese", "cotija", "peperoncino", "lime"]},
    ],
    "India": [
        {"nome": "Butter chicken", "chiave": "pollo", "firma": ["pollo", "burro", "pomodoro", "panna", "spezie garam masala"]},
        {"nome": "Pollo tikka masala", "chiave": "pollo", "firma": ["pollo", "yogurt", "pomodoro", "panna", "spezie"]},
        {"nome": "Biryani", "chiave": "riso basmati", "firma": ["riso basmati", "carne o verdure", "spezie", "zafferano"]},
        {"nome": "Dal makhani", "chiave": "lenticchie", "firma": ["lenticchie nere", "burro", "panna", "spezie"]},
        {"nome": "Palak paneer", "chiave": "paneer", "firma": ["spinaci", "paneer", "spezie", "aglio"]},
        {"nome": "Rogan josh", "chiave": "agnello", "firma": ["agnello", "yogurt", "spezie", "peperoncino kashmiri"]},
        {"nome": "Chana masala", "chiave": "ceci", "firma": ["ceci", "pomodoro", "cipolla", "spezie"]},
        {"nome": "Samosa", "chiave": "patate", "firma": ["pasta", "patate", "piselli", "spezie"]},
        {"nome": "Naan", "chiave": "farina", "firma": ["farina", "yogurt", "lievito"], "disc": "panificazione"},
        {"nome": "Dosa", "chiave": "riso", "firma": ["riso fermentato", "lenticchie urad", "ripieno di patate"]},
        {"nome": "Tandoori chicken", "chiave": "pollo", "firma": ["pollo", "yogurt", "spezie tandoori", "cottura tandoor"]},
        {"nome": "Aloo gobi", "chiave": "cavolfiore", "firma": ["patate", "cavolfiore", "curcuma", "spezie"]},
    ],
    "Thailandia": [
        {"nome": "Pad thai", "chiave": "noodles di riso", "firma": ["noodles di riso", "gamberi", "tofu", "arachidi", "tamarindo", "uova"]},
        {"nome": "Tom yum goong", "chiave": "gamberi", "firma": ["gamberi", "citronella", "galanga", "lime", "peperoncino"]},
        {"nome": "Green curry", "chiave": "latte di cocco", "firma": ["pasta di curry verde", "latte di cocco", "pollo", "basilico thai"]},
        {"nome": "Massaman curry", "chiave": "latte di cocco", "firma": ["pasta massaman", "latte di cocco", "manzo", "patate", "arachidi"]},
        {"nome": "Som tam", "chiave": "papaya", "firma": ["papaya verde", "lime", "peperoncino", "arachidi", "salsa di pesce"]},
        {"nome": "Pad krapow", "chiave": "basilico thai", "firma": ["carne macinata", "basilico thai", "peperoncino", "salsa di pesce"]},
        {"nome": "Tom kha gai", "chiave": "latte di cocco", "firma": ["pollo", "latte di cocco", "galanga", "citronella"]},
        {"nome": "Mango sticky rice", "chiave": "riso glutinoso", "firma": ["riso glutinoso", "mango", "latte di cocco"], "disc": "pasticceria"},
    ],
    "Vietnam / SE Asia": [
        {"nome": "Pho bo", "chiave": "manzo", "firma": ["noodles di riso", "brodo di manzo", "manzo", "erbe", "anice stellato"]},
        {"nome": "Banh mi", "chiave": "maiale", "firma": ["baguette", "maiale", "verdure in agrodolce", "coriandolo"]},
        {"nome": "Bun cha", "chiave": "maiale", "firma": ["noodles", "polpette di maiale", "erbe", "nuoc cham"]},
        {"nome": "Goi cuon (involtini)", "chiave": "gamberi", "firma": ["carta di riso", "gamberi", "vermicelli", "erbe"]},
        {"nome": "Nasi goreng", "chiave": "riso", "firma": ["riso", "kecap manis", "uova", "gamberetti", "scalogno"]},
        {"nome": "Satay", "chiave": "pollo", "firma": ["pollo", "spezie", "salsa di arachidi"]},
        {"nome": "Laksa", "chiave": "latte di cocco", "firma": ["noodles", "latte di cocco", "gamberi", "pasta di curry"]},
    ],
    "Medio Oriente": [
        {"nome": "Hummus", "chiave": "ceci", "firma": ["ceci", "tahini", "limone", "aglio", "olio"]},
        {"nome": "Falafel", "chiave": "ceci", "firma": ["ceci", "prezzemolo", "aglio", "cumino", "olio per friggere"]},
        {"nome": "Shawarma", "chiave": "carne", "firma": ["carne marinata", "spezie", "pane", "salsa tahini"]},
        {"nome": "Tabbouleh", "chiave": "prezzemolo", "firma": ["bulgur", "prezzemolo", "menta", "pomodoro", "limone"]},
        {"nome": "Baba ganoush", "chiave": "melanzane", "firma": ["melanzane", "tahini", "limone", "aglio"]},
        {"nome": "Kebab", "chiave": "carne", "firma": ["carne macinata", "spezie", "cipolla"]},
        {"nome": "Tagine di agnello", "chiave": "agnello", "firma": ["agnello", "albicocche", "spezie", "mandorle"]},
        {"nome": "Couscous", "chiave": "semola", "firma": ["couscous", "verdure", "carne", "brodo speziato"]},
        {"nome": "Baklava", "chiave": "frutta secca", "firma": ["pasta fillo", "noci", "miele", "sciroppo"], "disc": "pasticceria"},
        {"nome": "Fattoush", "chiave": "verdure", "firma": ["pane pita", "verdure", "sumac", "limone"]},
        {"nome": "Muhammara", "chiave": "peperoni", "firma": ["peperoni rossi", "noci", "melassa di melograno"]},
    ],
    "Francia": [
        {"nome": "Coq au vin", "chiave": "pollo", "firma": ["pollo", "vino rosso", "pancetta", "funghi", "cipolline"]},
        {"nome": "Boeuf bourguignon", "chiave": "manzo", "firma": ["manzo", "vino rosso di borgogna", "pancetta", "funghi", "carote"]},
        {"nome": "Ratatouille", "chiave": "verdure", "firma": ["melanzane", "zucchine", "peperoni", "pomodoro", "erbe di provenza"]},
        {"nome": "Bouillabaisse", "chiave": "pesce", "firma": ["pesce misto", "zafferano", "finocchio", "rouille", "pomodoro"]},
        {"nome": "Quiche lorraine", "chiave": "uova", "firma": ["pasta brisée", "uova", "panna", "pancetta"]},
        {"nome": "Confit di anatra", "chiave": "anatra", "firma": ["cosce d'anatra", "grasso d'anatra", "sale", "timo"]},
        {"nome": "Soupe à l'oignon", "chiave": "cipolla", "firma": ["cipolle", "brodo", "pane", "gruyère"]},
        {"nome": "Cassoulet", "chiave": "fagioli", "firma": ["fagioli bianchi", "salsiccia", "anatra", "pancetta"]},
        {"nome": "Sole meunière", "chiave": "pesce", "firma": ["sogliola", "burro", "farina", "limone", "prezzemolo"]},
        {"nome": "Crème brûlée", "chiave": "panna", "firma": ["panna", "tuorli", "zucchero", "vaniglia"], "disc": "pasticceria"},
        {"nome": "Tarte tatin", "chiave": "mele", "firma": ["mele", "caramello", "pasta brisée"], "disc": "pasticceria"},
        {"nome": "Croissant", "chiave": "farina", "firma": ["farina", "burro", "lievito", "latte"], "disc": "panificazione"},
        {"nome": "Macaron", "chiave": "mandorle", "firma": ["farina di mandorle", "albumi", "zucchero", "ganache"], "disc": "pasticceria"},
        {"nome": "Ratatouille", "chiave": "verdure", "firma": ["melanzane", "zucchine", "peperoni", "pomodoro"]},
    ],
    "USA / BBQ": [
        {"nome": "Brisket affumicato", "chiave": "manzo", "firma": ["punta di petto di manzo", "spezie", "affumicatura low and slow"]},
        {"nome": "Pulled pork", "chiave": "maiale", "firma": ["spalla di maiale", "spezie", "affumicatura", "salsa bbq"]},
        {"nome": "Ribs bbq", "chiave": "maiale", "firma": ["costine di maiale", "rub di spezie", "salsa bbq"]},
        {"nome": "Cheeseburger", "chiave": "manzo", "firma": ["macinato di manzo", "formaggio cheddar", "pane", "cetriolini"]},
        {"nome": "Mac and cheese", "chiave": "formaggio", "firma": ["pasta", "formaggio cheddar", "besciamella"]},
        {"nome": "Fried chicken", "chiave": "pollo", "firma": ["pollo", "buttermilk", "farina speziata", "olio per friggere"]},
        {"nome": "Clam chowder", "chiave": "vongole", "firma": ["vongole", "patate", "panna", "pancetta"]},
        {"nome": "New York cheesecake", "chiave": "formaggio fresco", "firma": ["cream cheese", "uova", "biscotti", "zucchero"], "disc": "pasticceria"},
    ],
    "Spagna": [
        {"nome": "Paella valenciana", "chiave": "riso", "firma": ["riso bomba", "pollo", "coniglio", "zafferano", "fagioli"]},
        {"nome": "Paella de marisco", "chiave": "riso", "firma": ["riso", "frutti di mare", "zafferano", "brodo di pesce"]},
        {"nome": "Tortilla española", "chiave": "patate", "firma": ["patate", "uova", "cipolla", "olio"]},
        {"nome": "Gazpacho", "chiave": "pomodoro", "firma": ["pomodoro", "peperoni", "cetriolo", "aglio", "pane"]},
        {"nome": "Patatas bravas", "chiave": "patate", "firma": ["patate", "salsa brava", "aioli"]},
        {"nome": "Pulpo a la gallega", "chiave": "polpo", "firma": ["polpo", "patate", "paprika", "olio"]},
        {"nome": "Croquetas de jamón", "chiave": "prosciutto", "firma": ["besciamella", "prosciutto", "pangrattato", "uova"]},
        {"nome": "Churros", "chiave": "farina", "firma": ["farina", "acqua", "olio per friggere", "cioccolato"], "disc": "pasticceria"},
    ],
    "Grecia": [
        {"nome": "Moussaka", "chiave": "melanzane", "firma": ["melanzane", "carne macinata", "besciamella", "pomodoro"]},
        {"nome": "Souvlaki", "chiave": "maiale", "firma": ["maiale", "limone", "origano", "olio"]},
        {"nome": "Gyros", "chiave": "carne", "firma": ["carne", "pita", "tzatziki", "cipolla"]},
        {"nome": "Insalata greca", "chiave": "feta", "firma": ["pomodoro", "cetriolo", "feta", "olive", "origano"]},
        {"nome": "Spanakopita", "chiave": "spinaci", "firma": ["pasta fillo", "spinaci", "feta", "uova"]},
        {"nome": "Tzatziki", "chiave": "yogurt", "firma": ["yogurt greco", "cetriolo", "aglio", "aneto"]},
        {"nome": "Baklava greca", "chiave": "frutta secca", "firma": ["pasta fillo", "noci", "miele"], "disc": "pasticceria"},
    ],
}
