# mappa_bakery_estesa.py - pani e lievitati canonici (non copyright: liste ingredienti = fatti)
BAKERY_ESTESA = [
    {"nome": "Baguette", "chiave": "farina", "firma": ["farina","acqua","sale","lievito"], "area": "Francia", "disciplina": "panificazione"},
    {"nome": "Ciabatta", "chiave": "farina", "firma": ["farina","acqua","sale","biga"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Pane di Altamura", "chiave": "semola", "firma": ["semola","acqua","sale","madre"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Pane Cafone", "chiave": "farina", "firma": ["farina","acqua","sale","madre"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Michetta", "chiave": "farina", "firma": ["farina","acqua","sale","malto"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Coppia Ferrarese", "chiave": "farina", "firma": ["farina","acqua","sale","strutto"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Pane Pugliese", "chiave": "semola", "firma": ["semola","acqua","sale","madre"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Focaccia Genovese", "chiave": "farina", "firma": ["farina","acqua","olio","sale"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Focaccia Barese", "chiave": "semola", "firma": ["semola","patata","acqua","olio","pomodorini"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Sourdough", "chiave": "farina", "firma": ["farina","acqua","sale","madre"], "area": "USA", "disciplina": "panificazione"},
    {"nome": "Bagel", "chiave": "farina", "firma": ["farina","acqua","malto","sale"], "area": "USA", "disciplina": "panificazione"},
    {"nome": "Pretzel", "chiave": "farina", "firma": ["farina","acqua","burro","soda"], "area": "Germania", "disciplina": "panificazione"},
    {"nome": "Brioche", "chiave": "farina", "firma": ["farina","uova","burro","zucchero","latte"], "area": "Francia", "disciplina": "panificazione"},
    {"nome": "Croissant", "chiave": "farina", "firma": ["farina","burro","acqua","zucchero","lievito"], "area": "Francia", "disciplina": "panificazione"},
    {"nome": "Pain au Chocolat", "chiave": "farina", "firma": ["farina","burro","cioccolato","lievito"], "area": "Francia", "disciplina": "panificazione"},
    {"nome": "Naan", "chiave": "farina", "firma": ["farina","yogurt","acqua","lievito"], "area": "India", "disciplina": "panificazione"},
    {"nome": "Pita", "chiave": "farina", "firma": ["farina","acqua","sale","lievito"], "area": "Grecia", "disciplina": "panificazione"},
    {"nome": "Focaccia di Recco", "chiave": "farina", "firma": ["farina","acqua","olio","crescenza"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Grissini Torinesi", "chiave": "farina", "firma": ["farina","acqua","olio","malto"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Taralli", "chiave": "farina", "firma": ["farina","vino bianco","olio","finocchietto"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Friselle", "chiave": "orzo", "firma": ["orzo","semola","acqua","sale"], "area": "Italia", "disciplina": "panificazione"},
    {"nome": "Pandoro", "chiave": "farina", "firma": ["farina","burro","uova","zucchero","vaniglia"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Panettone", "chiave": "farina", "firma": ["farina","burro","uova","canditi","uvetta","madre"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Colomba", "chiave": "farina", "firma": ["farina","burro","uova","canditi","mandorle"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Babà", "chiave": "farina", "firma": ["farina","uova","burro","rum"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Sfogliatella", "chiave": "farina", "firma": ["farina","semola","ricotta","canditi"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Cannoli Siciliani", "chiave": "farina", "firma": ["farina","ricotta","zucchero","cioccolato"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Pastiera Napoletana", "chiave": "farina", "firma": ["grano cotto","ricotta","canditi","fiori arancio"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Cassata Siciliana", "chiave": "pan di spagna", "firma": ["pan di spagna","ricotta","pasta reale","canditi"], "area": "Italia", "disciplina": "pasticceria"},
    {"nome": "Tiramisù", "chiave": "savoiardi", "firma": ["savoiardi","mascarpone","uova","caffè","cacao"], "area": "Italia", "disciplina": "pasticceria"},
]
