# mappa_cocktail_estesa.py - cocktail canonici (IBA + classici + moderni) per il serbatoio
COCKTAIL_ESTESI = [
    {"nome": "Aviation", "chiave": "gin", "firma": ["gin","maraschino","crème de violette","succo di limone"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Corpse Reviver #2", "chiave": "gin", "firma": ["gin","cointreau","lillet blanc","limone","assenzio"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Last Word", "chiave": "gin", "firma": ["gin","chartreuse verde","maraschino","lime"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Clover Club", "chiave": "gin", "firma": ["gin","lampone","limone","albume"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Vesper", "chiave": "gin", "firma": ["gin","vodka","lillet blanc"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Hanky Panky", "chiave": "gin", "firma": ["gin","vermouth rosso","fernet branca"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Bijou", "chiave": "gin", "firma": ["gin","chartreuse verde","vermouth rosso"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Gimlet", "chiave": "gin", "firma": ["gin","lime cordial"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Tom Collins", "chiave": "gin", "firma": ["gin","limone","zucchero","soda"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Gin Fizz", "chiave": "gin", "firma": ["gin","limone","zucchero","soda"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Ramos Gin Fizz", "chiave": "gin", "firma": ["gin","panna","albume","limone","lime","fiori arancio"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "White Lady", "chiave": "gin", "firma": ["gin","cointreau","limone"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "French 75", "chiave": "gin", "firma": ["gin","limone","zucchero","champagne"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Southside", "chiave": "gin", "firma": ["gin","limone","zucchero","menta"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Bee's Knees", "chiave": "gin", "firma": ["gin","limone","miele"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Martinez", "chiave": "gin", "firma": ["gin old tom","vermouth rosso","maraschino","bitter"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Boulevardier", "chiave": "bourbon", "firma": ["bourbon","vermouth rosso","campari"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Paper Plane", "chiave": "bourbon", "firma": ["bourbon","aperol","amaro nonino","limone"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Gold Rush", "chiave": "bourbon", "firma": ["bourbon","limone","miele"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Whiskey Sour", "chiave": "bourbon", "firma": ["bourbon","limone","zucchero","albume"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Penicillin", "chiave": "whisky", "firma": ["scotch","lime","miele","zenzero"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Rob Roy", "chiave": "whisky", "firma": ["scotch","vermouth rosso","bitter"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Rusty Nail", "chiave": "whisky", "firma": ["scotch","drambuie"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Vieux Carré", "chiave": "rye", "firma": ["rye","cognac","vermouth rosso","benedictine","bitter"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Sazerac", "chiave": "rye", "firma": ["rye","zucchero","peychaud","assenzio"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Mint Julep", "chiave": "bourbon", "firma": ["bourbon","menta","zucchero"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Mai Tai", "chiave": "rum", "firma": ["rum","orange curaçao","orgeat","lime"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Daiquiri", "chiave": "rum", "firma": ["rum","lime","zucchero"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Hemingway Daiquiri", "chiave": "rum", "firma": ["rum","maraschino","lime","pompelmo"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Piña Colada", "chiave": "rum", "firma": ["rum","crema di cocco","ananas"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Jungle Bird", "chiave": "rum", "firma": ["rum scuro","campari","ananas","lime"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Dark n Stormy", "chiave": "rum", "firma": ["rum scuro","ginger beer","lime"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Caipirinha", "chiave": "cachaça", "firma": ["cachaça","lime","zucchero"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Margarita", "chiave": "tequila", "firma": ["tequila","cointreau","lime"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Tommy's Margarita", "chiave": "tequila", "firma": ["tequila","lime","agave"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Paloma", "chiave": "tequila", "firma": ["tequila","pompelmo","lime","soda"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Naked and Famous", "chiave": "mezcal", "firma": ["mezcal","chartreuse gialla","aperol","lime"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Cosmopolitan", "chiave": "vodka", "firma": ["vodka","cointreau","lime","mirtillo rosso"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Espresso Martini", "chiave": "vodka", "firma": ["vodka","caffè","zucchero","liquore caffè"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Moscow Mule", "chiave": "vodka", "firma": ["vodka","lime","ginger beer"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Bloody Mary", "chiave": "vodka", "firma": ["vodka","pomodoro","limone","worcestershire","tabasco"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Sidecar", "chiave": "cognac", "firma": ["cognac","cointreau","limone"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Brandy Alexander", "chiave": "cognac", "firma": ["cognac","crème de cacao","panna"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Pisco Sour", "chiave": "pisco", "firma": ["pisco","lime","zucchero","albume","bitter"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Bramble", "chiave": "gin", "firma": ["gin","limone","zucchero","crème de mûre"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Bellini", "chiave": "prosecco", "firma": ["purea di pesca","prosecco"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Americano", "chiave": "campari", "firma": ["campari","vermouth rosso","soda"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Spritz", "chiave": "aperol", "firma": ["aperol","prosecco","soda"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Singapore Sling", "chiave": "gin", "firma": ["gin","cherry brandy","cointreau","benedictine","ananas","lime"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Zombie", "chiave": "rum", "firma": ["rum bianco","rum scuro","lime","falernum","assenzio"], "area": "Bar / Cocktail", "disciplina": "bar"},
    {"nome": "Grasshopper", "chiave": "crème de menthe", "firma": ["crème de menthe","crème de cacao","panna"], "area": "Bar / Cocktail", "disciplina": "bar"},
]
