# mappa_bar_iba.py
# COCKTAIL IBA UFFICIALI (mancanti) + espansione pasticceria e panificazione.
# IBA = International Bartenders Association: The Unforgettables, Contemporary Classics, New Era Drinks.

# ── COCKTAIL IBA (quelli non già presenti nelle altre mappe) ──
BAR_IBA = [
    # The Unforgettables
    {"nome": "Alexander", "chiave": "cognac", "firma": ["cognac", "crème de cacao", "panna"]},
    {"nome": "Angel Face", "chiave": "gin", "firma": ["gin", "calvados", "apricot brandy"]},
    {"nome": "Aviation", "chiave": "gin", "firma": ["gin", "maraschino", "crème de violette", "limone"]},
    {"nome": "Between the Sheets", "chiave": "rum", "firma": ["rum bianco", "cognac", "triple sec", "limone"]},
    {"nome": "Casino", "chiave": "gin", "firma": ["gin", "maraschino", "orange bitters", "limone"]},
    {"nome": "Clover Club", "chiave": "gin", "firma": ["gin", "lampone", "limone", "albume"]},
    {"nome": "Daiquiri", "chiave": "rum", "firma": ["rum bianco", "lime", "zucchero"]},
    {"nome": "Derby", "chiave": "gin", "firma": ["gin", "peach bitters", "menta"]},
    {"nome": "Martinez", "chiave": "gin", "firma": ["gin", "vermouth rosso", "maraschino", "angostura"]},
    {"nome": "Mary Pickford", "chiave": "rum", "firma": ["rum bianco", "ananas", "granatina", "maraschino"]},
    {"nome": "Monkey Gland", "chiave": "gin", "firma": ["gin", "arancia", "granatina", "assenzio"]},
    {"nome": "Negroni", "chiave": "gin", "firma": ["gin", "vermouth rosso", "campari"]},
    {"nome": "Old Fashioned", "chiave": "whiskey", "firma": ["bourbon", "zucchero", "angostura"]},
    {"nome": "Paradise", "chiave": "gin", "firma": ["gin", "apricot brandy", "arancia"]},
    {"nome": "Planter's Punch", "chiave": "rum", "firma": ["rum scuro", "arancia", "ananas", "limone", "granatina"]},
    {"nome": "Porto Flip", "chiave": "porto", "firma": ["brandy", "porto", "tuorlo"]},
    {"nome": "Ramos Gin Fizz", "chiave": "gin", "firma": ["gin", "limone", "lime", "panna", "albume", "acqua di fiori d'arancio", "soda"]},
    {"nome": "Rusty Nail", "chiave": "whiskey", "firma": ["scotch", "drambuie"]},
    {"nome": "Sazerac", "chiave": "whiskey", "firma": ["rye whiskey", "assenzio", "zucchero", "peychaud's"]},
    {"nome": "Sidecar", "chiave": "cognac", "firma": ["cognac", "triple sec", "limone"]},
    {"nome": "Stinger", "chiave": "cognac", "firma": ["cognac", "crème de menthe"]},
    {"nome": "Tuxedo", "chiave": "gin", "firma": ["gin", "vermouth dry", "maraschino", "assenzio"]},
    {"nome": "Whiskey Sour", "chiave": "whiskey", "firma": ["bourbon", "limone", "zucchero", "albume"]},
    {"nome": "White Lady", "chiave": "gin", "firma": ["gin", "triple sec", "limone"]},
    # Contemporary Classics
    {"nome": "Bramble", "chiave": "gin", "firma": ["gin", "limone", "zucchero", "crème de mûre"]},
    {"nome": "Cosmopolitan", "chiave": "vodka", "firma": ["vodka", "triple sec", "mirtillo rosso", "lime"]},
    {"nome": "Cuba Libre", "chiave": "rum", "firma": ["rum", "cola", "lime"]},
    {"nome": "French Connection", "chiave": "cognac", "firma": ["cognac", "amaretto"]},
    {"nome": "French Martini", "chiave": "vodka", "firma": ["vodka", "lampone", "ananas"]},
    {"nome": "Kir", "chiave": "vino bianco", "firma": ["vino bianco", "crème de cassis"]},
    {"nome": "Kir Royal", "chiave": "champagne", "firma": ["champagne", "crème de cassis"]},
    {"nome": "Long Island Iced Tea", "chiave": "vodka", "firma": ["vodka", "gin", "rum", "tequila", "triple sec", "limone", "cola"]},
    {"nome": "Mai Tai", "chiave": "rum", "firma": ["rum", "curaçao", "orgeat", "lime"]},
    {"nome": "Margarita", "chiave": "tequila", "firma": ["tequila", "triple sec", "lime"]},
    {"nome": "Mimosa", "chiave": "champagne", "firma": ["champagne", "succo d'arancia"]},
    {"nome": "Mint Julep", "chiave": "whiskey", "firma": ["bourbon", "menta", "zucchero"]},
    {"nome": "Mojito", "chiave": "rum", "firma": ["rum bianco", "lime", "menta", "zucchero", "soda"]},
    {"nome": "Moscow Mule", "chiave": "vodka", "firma": ["vodka", "ginger beer", "lime"]},
    {"nome": "Piña Colada", "chiave": "rum", "firma": ["rum", "latte di cocco", "ananas"]},
    {"nome": "Sea Breeze", "chiave": "vodka", "firma": ["vodka", "mirtillo rosso", "pompelmo"]},
    {"nome": "Sex on the Beach", "chiave": "vodka", "firma": ["vodka", "peach schnapps", "arancia", "mirtillo"]},
    {"nome": "Tequila Sunrise", "chiave": "tequila", "firma": ["tequila", "arancia", "granatina"]},
    {"nome": "Zombie", "chiave": "rum", "firma": ["rum scuro", "rum bianco", "apricot brandy", "lime", "granatina"]},
    # New Era
    {"nome": "Bellini", "chiave": "prosecco", "firma": ["prosecco", "purea di pesca"]},
    {"nome": "Black Russian", "chiave": "vodka", "firma": ["vodka", "liquore al caffè"]},
    {"nome": "White Russian", "chiave": "vodka", "firma": ["vodka", "liquore al caffè", "panna"]},
    {"nome": "Bloody Mary", "chiave": "vodka", "firma": ["vodka", "succo di pomodoro", "limone", "worcester", "tabasco"]},
    {"nome": "Caipirinha", "chiave": "cachaça", "firma": ["cachaça", "lime", "zucchero"]},
    {"nome": "Dark 'n' Stormy", "chiave": "rum", "firma": ["rum scuro", "ginger beer", "lime"]},
    {"nome": "Dirty Martini", "chiave": "vodka", "firma": ["vodka", "vermouth dry", "salamoia di olive"]},
    {"nome": "Espresso Martini", "chiave": "vodka", "firma": ["vodka", "caffè espresso", "liquore al caffè"]},
    {"nome": "French 75", "chiave": "gin", "firma": ["gin", "champagne", "limone", "zucchero"]},
    {"nome": "Gin Fizz", "chiave": "gin", "firma": ["gin", "limone", "zucchero", "soda"]},
    {"nome": "Golden Dream", "chiave": "liquore", "firma": ["galliano", "triple sec", "arancia", "panna"]},
    {"nome": "Grasshopper", "chiave": "liquore", "firma": ["crème de menthe", "crème de cacao", "panna"]},
    {"nome": "Hemingway Special", "chiave": "rum", "firma": ["rum", "maraschino", "pompelmo", "lime"]},
    {"nome": "Horse's Neck", "chiave": "cognac", "firma": ["cognac", "ginger ale", "angostura"]},
    {"nome": "Irish Coffee", "chiave": "whiskey", "firma": ["whiskey irlandese", "caffè", "zucchero", "panna"]},
    {"nome": "Kamikaze", "chiave": "vodka", "firma": ["vodka", "triple sec", "lime"]},
    {"nome": "Lemon Drop Martini", "chiave": "vodka", "firma": ["vodka", "triple sec", "limone", "zucchero"]},
    {"nome": "Mimosa", "chiave": "champagne", "firma": ["champagne", "arancia"]},
    {"nome": "Paloma", "chiave": "tequila", "firma": ["tequila", "pompelmo", "lime", "soda"]},
    {"nome": "Pisco Sour", "chiave": "pisco", "firma": ["pisco", "limone", "zucchero", "albume", "angostura"]},
    {"nome": "Russian Spring Punch", "chiave": "vodka", "firma": ["vodka", "crème de cassis", "limone", "champagne"]},
    {"nome": "Singapore Sling", "chiave": "gin", "firma": ["gin", "cherry brandy", "ananas", "lime", "bénédictine"]},
    {"nome": "Spritz Veneziano", "chiave": "aperol", "firma": ["aperol", "prosecco", "soda"]},
    {"nome": "Tommy's Margarita", "chiave": "tequila", "firma": ["tequila", "lime", "agave"]},
    {"nome": "Vampiro", "chiave": "tequila", "firma": ["tequila", "succo di pomodoro", "arancia", "lime", "peperoncino"]},
    {"nome": "Vesper", "chiave": "gin", "firma": ["gin", "vodka", "lillet blanc"]},
    {"nome": "Yellow Bird", "chiave": "rum", "firma": ["rum", "galliano", "triple sec", "lime"]},
    # twist / classici moderni comuni al banco
    {"nome": "Boulevardier", "chiave": "whiskey", "firma": ["bourbon", "vermouth rosso", "campari"]},
    {"nome": "Americano", "chiave": "bitter", "firma": ["campari", "vermouth rosso", "soda"]},
    {"nome": "Garibaldi", "chiave": "bitter", "firma": ["campari", "succo d'arancia"]},
    {"nome": "Penicillin", "chiave": "whiskey", "firma": ["scotch", "zenzero", "miele", "limone"]},
    {"nome": "Paper Plane", "chiave": "whiskey", "firma": ["bourbon", "aperol", "amaro nonino", "limone"]},
    {"nome": "Last Word", "chiave": "gin", "firma": ["gin", "chartreuse", "maraschino", "lime"]},
    {"nome": "Naked and Famous", "chiave": "mezcal", "firma": ["mezcal", "aperol", "chartreuse", "lime"]},
    {"nome": "Gimlet", "chiave": "gin", "firma": ["gin", "lime cordial"]},
    {"nome": "Tom Collins", "chiave": "gin", "firma": ["gin", "limone", "zucchero", "soda"]},
]

# ── ESPANSIONE PASTICCERIA ──
PASTICCERIA_EXTRA = [
    {"nome": "Bignè alla crema", "chiave": "crema", "firma": ["pasta choux", "crema pasticcera"]},
    {"nome": "Crostata di frutta", "chiave": "crema", "firma": ["pasta frolla", "crema pasticcera", "frutta"]},
    {"nome": "Torta della nonna", "chiave": "crema", "firma": ["pasta frolla", "crema", "pinoli"]},
    {"nome": "Crema pasticcera", "chiave": "uova", "firma": ["latte", "tuorli", "zucchero", "amido", "vaniglia"]},
    {"nome": "Pan di Spagna", "chiave": "uova", "firma": ["uova", "zucchero", "farina"]},
    {"nome": "Bavarese", "chiave": "panna", "firma": ["crema inglese", "gelatina", "panna"]},
    {"nome": "Mousse al cioccolato", "chiave": "cioccolato", "firma": ["cioccolato", "panna", "uova"]},
    {"nome": "Semifreddo", "chiave": "panna", "firma": ["panna", "meringa", "zucchero"]},
    {"nome": "Millefoglie", "chiave": "crema", "firma": ["pasta sfoglia", "crema", "zucchero a velo"]},
    {"nome": "Saint Honoré", "chiave": "crema", "firma": ["pasta sfoglia", "bignè", "crema chantilly", "caramello"]},
    {"nome": "Cheesecake", "chiave": "formaggio fresco", "firma": ["biscotti", "formaggio fresco", "panna"]},
    {"nome": "Panna cotta ai frutti di bosco", "chiave": "panna", "firma": ["panna", "gelatina", "frutti di bosco"]},
    {"nome": "Bignè di San Giuseppe", "chiave": "crema", "firma": ["pasta choux", "crema", "amarena"]},
    {"nome": "Crostata di ricotta", "chiave": "ricotta", "firma": ["pasta frolla", "ricotta", "zucchero"]},
    {"nome": "Torta caprese", "chiave": "cioccolato", "firma": ["mandorle", "cioccolato", "burro", "uova"]},
    {"nome": "Tiramisù classico", "chiave": "mascarpone", "firma": ["savoiardi", "mascarpone", "caffè", "uova", "cacao"]},
    {"nome": "Zuppa inglese", "chiave": "crema", "firma": ["savoiardi", "crema", "alchermes", "cioccolato"]},
    {"nome": "Profiteroles al cioccolato", "chiave": "crema", "firma": ["bignè", "panna", "cioccolato"]},
    {"nome": "Éclair al caffè", "chiave": "crema", "firma": ["pasta choux", "crema al caffè", "glassa"]},
    {"nome": "Crème caramel", "chiave": "uova", "firma": ["uova", "latte", "zucchero", "caramello"]},
    {"nome": "Tarte au citron", "chiave": "limone", "firma": ["pasta frolla", "crema al limone", "meringa"]},
    {"nome": "Fondente al cioccolato", "chiave": "cioccolato", "firma": ["cioccolato", "burro", "uova", "farina"]},
    {"nome": "Panettone artigianale", "chiave": "farina", "firma": ["farina", "lievito madre", "burro", "canditi", "uvetta"]},
    {"nome": "Colomba", "chiave": "farina", "firma": ["farina", "lievito madre", "burro", "canditi", "mandorle"]},
    {"nome": "Torta Sacher", "chiave": "cioccolato", "firma": ["cioccolato", "marmellata di albicocche"]},
]

# ── ESPANSIONE PANIFICAZIONE (inclusa PIZZERIA) ──
PANIFICAZIONE_EXTRA = [
    {"nome": "Pizza napoletana STG", "chiave": "farina", "firma": ["impasto", "pomodoro san marzano", "mozzarella di bufala", "basilico"]},
    {"nome": "Pizza in teglia romana", "chiave": "farina", "firma": ["impasto ad alta idratazione", "pomodoro", "mozzarella"]},
    {"nome": "Pizza al taglio", "chiave": "farina", "firma": ["impasto", "condimenti vari"]},
    {"nome": "Focaccia pugliese", "chiave": "farina", "firma": ["farina", "patata", "pomodorini", "olive"]},
    {"nome": "Focaccia con lievito madre", "chiave": "farina", "firma": ["farina", "lievito madre", "olio", "sale"]},
    {"nome": "Pane con lievito madre", "chiave": "farina", "firma": ["farina", "lievito madre", "acqua", "sale"]},
    {"nome": "Pane integrale", "chiave": "farina integrale", "firma": ["farina integrale", "lievito", "acqua"]},
    {"nome": "Baguette", "chiave": "farina", "firma": ["farina", "lievito", "acqua", "sale"]},
    {"nome": "Ciabatta", "chiave": "farina", "firma": ["farina", "lievito", "acqua ad alta idratazione"]},
    {"nome": "Pane di semola", "chiave": "semola", "firma": ["semola rimacinata", "lievito madre", "acqua"]},
    {"nome": "Grissini", "chiave": "farina", "firma": ["farina", "olio", "lievito"]},
    {"nome": "Bagel", "chiave": "farina", "firma": ["farina", "lievito", "malto", "bollitura"]},
    {"nome": "Brioche", "chiave": "farina", "firma": ["farina", "burro", "uova", "lievito"]},
    {"nome": "Cornetto italiano", "chiave": "farina", "firma": ["farina", "burro", "uova", "lievito"]},
    {"nome": "Pane carasau", "chiave": "semola", "firma": ["semola", "acqua", "lievito"]},
    {"nome": "Piadina romagnola", "chiave": "farina", "firma": ["farina", "strutto", "acqua"]},
    {"nome": "Pane di Altamura", "chiave": "semola", "firma": ["semola di grano duro", "lievito madre", "acqua"]},
]
