# Mappa nomi Ahn (EN) -> italiano, estratta da routes/api.py per riuso.
NOMI_IT = {
            "roasted beef":"manzo arrosto","beef":"manzo","chicken":"pollo",
            "pork":"maiale","lamb":"agnello","turkey":"tacchino",
            "salmon":"salmone","tuna":"tonno","shrimp":"gambero","cod":"merluzzo",
            "tomato":"pomodoro","garlic":"aglio","onion":"cipolla","carrot":"carota",
            "celery":"sedano","mushroom":"fungo","porcini mushroom":"porcini",
            "potato":"patata","eggplant":"melanzana","bell pepper":"peperone",
            "pumpkin":"zucca","zucchini":"zucchine",
            "apple":"mela","pear":"pera","strawberry":"fragola","raspberry":"lampone",
            "blueberry":"mirtillo","orange":"arancia","lemon":"limone","lime":"lime",
            "banana":"banana","pineapple":"ananas","mango":"mango","coconut":"cocco",
            "butter":"burro","cream":"panna","milk":"latte","cheese":"formaggio",
            "parmesan":"parmigiano","mozzarella":"mozzarella","yogurt":"yogurt",
            "egg":"uovo","olive oil":"olio d'oliva","sesame":"sesamo",
            "almond":"mandorla","hazelnut":"nocciola","walnut":"noce","peanut":"arachide",
            "coffee":"caffè","espresso":"espresso","tea":"tè","cocoa":"cacao",
            "chocolate":"cioccolato","vanilla":"vaniglia","honey":"miele","sugar":"zucchero",
            "basil":"basilico","rosemary":"rosmarino","thyme":"timo","mint":"menta",
            "parsley":"prezzemolo","cinnamon":"cannella","ginger":"zenzero",
            "black pepper":"pepe nero","chili":"peperoncino",
            "red wine":"vino rosso","white wine":"vino bianco","beer":"birra",
            "rum":"rum","whiskey":"whisky","gin":"gin","vodka":"vodka",
            "vinegar":"aceto","soy sauce":"salsa di soia",
            "mandarin":"mandarino","tangerine":"mandarino","grapefruit":"pompelmo",
            "concord grape":"uva concord","grape":"uva","fig":"fico",
            "leek":"porro","nira":"erba cipollina cinese","chive":"erba cipollina",
            "cheddar cheese":"cheddar","brie":"brie","camembert":"camembert",
            "cucumber":"cetriolo","zucchini":"zucchine","pumpkin":"zucca",
            "raw beef":"manzo crudo","cooked beef":"manzo cotto",
            "pork meat":"carne di maiale","lamb meat":"carne d'agnello",
            "white bread":"pane bianco","wheat bread":"pane di frumento",
            "rice":"riso","corn":"mais","oat":"avena",
            "olive":"oliva","capers":"capperi","anchovy":"acciuga",
            "lobster":"aragosta","crab":"granchio","mussel":"cozza","oyster":"ostrica",
            "lemon juice":"succo di limone","orange juice":"succo d'arancia",
            "apple juice":"succo di mela","tomato juice":"succo di pomodoro",
            "black coffee":"caffè nero","roasted coffee":"caffè tostato",
            "black tea":"tè nero","green tea":"tè verde","white tea":"tè bianco",
            "chamomile":"camomilla","peppermint":"menta piperita",
            "dark chocolate":"cioccolato fondente","milk chocolate":"cioccolato al latte",
            "caramel":"caramello","maple syrup":"sciroppo d'acero",
            "saffron":"zafferano","turmeric":"curcuma","cardamom":"cardamomo",
            "clove":"chiodo di garofano","nutmeg":"noce moscata","anise":"anice",
            "lavender":"lavanda","rose":"rosa","jasmine":"gelsomino",
            "citrus":"agrumi","citrus peel":"scorza d'agrumi","bitter orange":"arancia amara",
            "lemongrass":"citronella","kumquat":"kumquat","bergamot":"bergamotto",
            "grapefruit":"pompelmo","yuzu":"yuzu","blood orange":"arancia rossa",
            "elderflower":"fiori di sambuco","hibiscus":"ibisco","juniper":"ginepro",
            "coriander":"coriandolo","fennel":"finocchio","dill":"aneto","tarragon":"dragoncello",
            "sage":"salvia","oregano":"origano","marjoram":"maggiorana","bay leaf":"alloro",
            "star anise":"anice stellato","licorice":"liquirizia","cocoa powder":"cacao in polvere",
            "roasted almond":"mandorla tostata","pistachio":"pistacchio","pecan":"noce pecan",
            "cashew":"anacardo","macadamia":"macadamia","chestnut":"castagna",
            "cranberry":"mirtillo rosso","blackberry":"mora","cherry":"ciliegia","peach":"pesca",
            "apricot":"albicocca","plum":"prugna","melon":"melone","watermelon":"anguria",
            "passion fruit":"frutto della passione","lychee":"litchi","papaya":"papaya",
            "guava":"guava","kiwi":"kiwi","pomegranate":"melograno","date":"dattero",
            "raisin":"uvetta","prune":"prugna secca","currant":"ribes",
}
