# Mappa nomi Ahn (EN) -> italiano, estratta da routes/api.py per riuso.
NOMI_IT = {
            "roasted beef":"manzo arrosto","beef":"manzo","chicken":"pollo",
            "pork":"maiale","lamb":"agnello","turkey":"tacchino",
            "salmon":"salmone","tuna":"tonno","shrimp":"gambero","cod":"merluzzo",
            "tomato":"pomodoro","garlic":"aglio","onion":"cipolla","carrot":"carota",
            "celery":"sedano","mushroom":"fungo","porcini mushroom":"porcini",
            "potato":"patata","eggplant":"melanzana","bell pepper":"peperone",
            "pumpkin":"zucca","zucchini":"zucchine",
            "apple":"mela","pear":"pera","strawberry":"fragola","raspberry":"lampone",
            "blueberry":"mirtillo","orange":"arancia","lemon":"limone","lime":"lime",
            "banana":"banana","pineapple":"ananas","mango":"mango","coconut":"cocco",
            "butter":"burro","cream":"panna","milk":"latte","cheese":"formaggio",
            "parmesan":"parmigiano","mozzarella":"mozzarella","yogurt":"yogurt",
            "egg":"uovo","olive oil":"olio d'oliva","sesame":"sesamo",
            "almond":"mandorla","hazelnut":"nocciola","walnut":"noce","peanut":"arachide",
            "coffee":"caffè","espresso":"espresso","tea":"tè","cocoa":"cacao",
            "chocolate":"cioccolato","vanilla":"vaniglia","honey":"miele","sugar":"zucchero",
            "basil":"basilico","rosemary":"rosmarino","thyme":"timo","mint":"menta",
            "parsley":"prezzemolo","cinnamon":"cannella","ginger":"zenzero",
            "black pepper":"pepe nero","chili":"peperoncino",
            "red wine":"vino rosso","white wine":"vino bianco","beer":"birra",
            "rum":"rum","whiskey":"whisky","gin":"gin","vodka":"vodka",
            "vinegar":"aceto","soy sauce":"salsa di soia",
            "mandarin":"mandarino","tangerine":"mandarino","grapefruit":"pompelmo",
            "concord grape":"uva concord","grape":"uva","fig":"fico",
            "leek":"porro","nira":"erba cipollina cinese","chive":"erba cipollina",
            "cheddar cheese":"cheddar","brie":"brie","camembert":"camembert",
            "cucumber":"cetriolo","zucchini":"zucchine","pumpkin":"zucca",
            "raw beef":"manzo crudo","cooked beef":"manzo cotto",
            "pork meat":"carne di maiale","lamb meat":"carne d'agnello",
            "white bread":"pane bianco","wheat bread":"pane di frumento",
            "rice":"riso","corn":"mais","oat":"avena",
            "olive":"oliva","capers":"capperi","anchovy":"acciuga",
            "lobster":"aragosta","crab":"granchio","mussel":"cozza","oyster":"ostrica",
            "lemon juice":"succo di limone","orange juice":"succo d'arancia",
            "apple juice":"succo di mela","tomato juice":"succo di pomodoro",
            "black coffee":"caffè nero","roasted coffee":"caffè tostato",
            "black tea":"tè nero","green tea":"tè verde","white tea":"tè bianco",
            "chamomile":"camomilla","peppermint":"menta piperita",
            "dark chocolate":"cioccolato fondente","milk chocolate":"cioccolato al latte",
            "caramel":"caramello","maple syrup":"sciroppo d'acero",
            "saffron":"zafferano","turmeric":"curcuma","cardamom":"cardamomo",
            "clove":"chiodo di garofano","nutmeg":"noce moscata","anise":"anice",
            "lavender":"lavanda","rose":"rosa","jasmine":"gelsomino",
            "citrus":"agrumi","citrus peel":"scorza d'agrumi","bitter orange":"arancia amara",
            "lemongrass":"citronella","kumquat":"kumquat","bergamot":"bergamotto",
            "grapefruit":"pompelmo","yuzu":"yuzu","blood orange":"arancia rossa",
            "elderflower":"fiori di sambuco","hibiscus":"ibisco","juniper":"ginepro",
            "coriander":"coriandolo","fennel":"finocchio","dill":"aneto","tarragon":"dragoncello",
            "sage":"salvia","oregano":"origano","marjoram":"maggiorana","bay leaf":"alloro",
            "star anise":"anice stellato","licorice":"liquirizia","cocoa powder":"cacao in polvere",
            "roasted almond":"mandorla tostata","pistachio":"pistacchio","pecan":"noce pecan",
            "cashew":"anacardo","macadamia":"macadamia","chestnut":"castagna",
            "cranberry":"mirtillo rosso","blackberry":"mora","cherry":"ciliegia","peach":"pesca",
            "apricot":"albicocca","plum":"prugna","melon":"melone","watermelon":"anguria",
            "passion fruit":"frutto della passione","lychee":"litchi","papaya":"papaya",
            "guava":"guava","kiwi":"kiwi","pomegranate":"melograno","date":"dattero",
            "raisin":"uvetta","prune":"prugna secca","currant":"ribes",
}


# Traduzioni aggiuntive per gli ingredienti Ahn da attivare (ampliamento copertura IT).
NOMI_IT_EXTRA = {
    "angelica": "angelica", "anise": "anice", "anise seed": "semi di anice",
    "apple brandy": "brandy di mele", "armagnac": "armagnac", "artemisia": "artemisia",
    "balm": "melissa", "bartlett pear": "pera williams", "bay": "alloro", "bean": "fagiolo",
    "beech": "faggio", "beef broth": "brodo di manzo", "beef liver": "fegato di manzo",
    "berry": "bacca", "bitter orange": "arancia amara", "black bean": "fagiolo nero",
    "blackberry brandy": "brandy di more", "black currant": "ribes nero",
    "black mustard seed oil": "olio di senape nera", "black raspberry": "lampone nero",
    "black sesame seed": "sesamo nero", "camembert cheese": "camembert",
    "cereal": "cereali", "port wine": "porto", "lima bean": "fagiolo di Lima",
    "orange flower": "fiori d'arancio", "brown rice": "riso integrale",
    "cheddar cheese": "cheddar", "goat cheese": "formaggio di capra",
    "blue cheese": "formaggio erborinato", "cottage cheese": "fiocchi di latte",
    "cream cheese": "formaggio spalmabile", "swiss cheese": "emmental",
    "buttermilk": "latticello", "sour cream": "panna acida", "whey": "siero di latte",
    "cognac": "cognac", "brandy": "brandy", "sherry": "sherry", "vermouth": "vermouth",
    "champagne": "champagne", "sake": "sakè", "cider": "sidro", "mead": "idromele",
    "gin": "gin", "vodka": "vodka", "tequila": "tequila", "whisky": "whisky",
    "bourbon whiskey": "bourbon", "scotch whisky": "scotch", "kirsch": "kirsch",
    "cabbage": "cavolo", "cauliflower": "cavolfiore", "brussels sprout": "cavoletto di Bruxelles",
    "kale": "cavolo riccio", "collard": "cavolo verde", "turnip": "rapa", "rutabaga": "rutabaga",
    "radish": "ravanello", "horseradish": "rafano", "parsnip": "pastinaca",
    "sweet potato": "patata dolce", "yam": "igname", "cassava": "manioca",
    "okra": "okra", "squash": "zucca", "zucchini": "zucchina", "cucumber": "cetriolo",
    "watercress": "crescione", "endive": "indivia", "escarole": "scarola",
    "leek": "porro", "shallot": "scalogno", "scallion": "cipollotto", "chive": "erba cipollina",
    "fennel": "finocchio", "celery": "sedano", "celeriac": "sedano rapa",
    "lettuce": "lattuga", "spinach": "spinaci", "chard": "bietola", "arugula": "rucola",
    "mustard greens": "senape (foglie)", "dandelion": "tarassaco",
    "lentil": "lenticchia", "chickpea": "cece", "kidney bean": "fagiolo rosso",
    "navy bean": "fagiolo bianco", "pinto bean": "fagiolo pinto", "soybean": "soia",
    "green bean": "fagiolino", "pea": "pisello", "snow pea": "taccola", "fava bean": "fava",
    "peanut": "arachide", "cashew": "anacardo", "macadamia": "macadamia",
    "pine nut": "pinolo", "chestnut": "castagna", "brazil nut": "noce del Brasile",
    "poppy seed": "semi di papavero", "sunflower seed": "semi di girasole",
    "pumpkin seed": "semi di zucca", "flaxseed": "semi di lino", "chia": "chia",
    "apricot": "albicocca", "nectarine": "nettarina", "quince": "mela cotogna",
    "persimmon": "cachi", "pomegranate": "melograno", "date": "dattero", "fig": "fico",
    "guava": "guava", "papaya": "papaya", "passion fruit": "frutto della passione",
    "lychee": "litchi", "kiwi": "kiwi", "cranberry": "mirtillo rosso",
    "gooseberry": "uva spina", "elderberry": "sambuco", "boysenberry": "boysenberry",
    "mulberry": "gelso", "loganberry": "loganberry", "tangerine": "mandarino",
    "clementine": "clementina", "kumquat": "kumquat", "yuzu": "yuzu", "citron": "cedro",
    "grapefruit": "pompelmo", "lime": "lime", "blood orange": "arancia rossa",
    "cardamom": "cardamomo", "clove": "chiodi di garofano", "coriander": "coriandolo",
    "cumin": "cumino", "fenugreek": "fieno greco", "turmeric": "curcuma",
    "saffron": "zafferano", "star anise": "anice stellato", "allspice": "pimento",
    "caraway": "carvi", "juniper": "ginepro", "mace": "macis", "sumac": "sommacco",
    "tarragon": "dragoncello", "marjoram": "maggiorana", "savory": "santoreggia",
    "lovage": "levistico", "sorrel": "acetosa", "chervil": "cerfoglio",
    "lemongrass": "citronella", "galangal": "galanga", "kaffir lime": "lime kaffir",
    "wasabi": "wasabi", "miso": "miso", "tofu": "tofu", "tempeh": "tempeh",
    "seaweed": "alga", "nori": "alga nori", "kombu": "alga kombu", "dashi": "dashi",
    "oyster": "ostrica", "clam": "vongola", "mussel": "cozza", "scallop": "capasanta",
    "squid": "calamaro", "octopus": "polpo", "crab": "granchio", "lobster": "aragosta",
    "anchovy": "acciuga", "sardine": "sardina", "mackerel": "sgombro", "herring": "aringa",
    "trout": "trota", "sea bass": "branzino", "sea bream": "orata", "halibut": "ippoglosso",
    "eel": "anguilla", "caviar": "caviale", "roe": "uova di pesce",
    "duck": "anatra", "goose": "oca", "quail": "quaglia", "rabbit": "coniglio",
    "venison": "cervo", "veal": "vitello", "lamb": "agnello", "mutton": "montone",
    "ham": "prosciutto", "bacon": "pancetta", "sausage": "salsiccia", "salami": "salame",
    "prosciutto": "prosciutto crudo", "pancetta": "pancetta", "chorizo": "chorizo",
    "molasses": "melassa", "maple syrup": "sciroppo d'acero", "agave": "agave",
    "brown sugar": "zucchero di canna", "muscovado": "muscovado",
    "cocoa": "cacao", "cocoa butter": "burro di cacao", "carob": "carruba",
    "vanilla": "vaniglia", "cinnamon": "cannella", "nutmeg": "noce moscata",
    "coconut": "cocco", "coconut milk": "latte di cocco", "almond": "mandorla",
    "hazelnut": "nocciola", "walnut": "noce", "pistachio": "pistacchio", "pecan": "noce pecan",
    "oat": "avena", "barley": "orzo", "rye": "segale", "buckwheat": "grano saraceno",
    "millet": "miglio", "quinoa": "quinoa", "bulgur": "bulgur", "couscous": "couscous",
    "polenta": "polenta", "semolina": "semola", "bran": "crusca", "wheat germ": "germe di grano",
    "artichoke": "carciofo", "asparagus": "asparago", "avocado": "avocado",
    "beet": "barbabietola", "bell pepper": "peperone", "eggplant": "melanzana",
    "mushroom": "fungo", "truffle": "tartufo", "shiitake": "shiitake", "porcini": "porcino",
    "tomato": "pomodoro", "potato": "patata", "baked potato": "patata al forno",
}
# unisci EXTRA nella mappa principale (EXTRA non sovrascrive le traduzioni curate esistenti)
for _k, _v in NOMI_IT_EXTRA.items():
    NOMI_IT.setdefault(_k, _v)
