# ============================================================
# routes/legal.py — pagine legali/informative (privacy, trust,
# cookie, termini, come-funziona-ai). HTML inline, nessuna dipendenza
# da app.py. Route spostate senza modifiche (@app.route -> @bp.route).
# ============================================================
from flask import Blueprint, request

bp = Blueprint("legal", __name__)


@bp.route("/privacy")
def privacy():
    """LE2 — Privacy policy (testo minimo legale, da aggiornare con consulente)."""
    return """<!DOCTYPE html><html lang="it"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Privacy Policy — Matter</title>
<style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;padding:0 20px;line-height:1.7;color:#1A1A18}
h1{font-size:24px;margin-bottom:8px}h2{font-size:18px;margin-top:32px}p,li{font-size:15px}</style>
</head><body>
<h1>Privacy Policy — Matter</h1>
<p><strong>Ultimo aggiornamento:</strong> luglio 2026</p>
<h2>Chi siamo</h2>
<p>Matter è uno strumento scientifico per professionisti F&B. Il titolare del trattamento è il soggetto che gestisce il servizio.</p>
<h2>Dati raccolti</h2>
<ul>
<li><strong>Domande al grafo:</strong> testo delle domande, fenomeni trovati, tipo di risposta. Conservati per migliorare il servizio.</li>
<li><strong>Account:</strong> email e password (in hash). Conservati fino alla cancellazione dell'account.</li>
<li><strong>Cookie tecnici:</strong> necessari per il funzionamento. Nessun cookie di profilazione.</li>
</ul>
<h2>Trasferimento dati</h2>
<p>Le domande sono processate da Anthropic (USA) e Mistral (FR) tramite API. Entrambi dispongono di garanzie adeguate per il trasferimento extra-UE.</p>
<h2>I tuoi diritti</h2>
<p>Hai diritto di accesso, rettifica, cancellazione, portabilità e opposizione. Contatta il titolare per esercitarli.</p>
<h2>Cookie</h2>
<p>Usiamo solo cookie tecnici essenziali. Puoi rifiutare i cookie non essenziali dal banner.</p>
<p><a href="/">← Torna a Matter</a></p>
</body></html>""", 200, {'Content-Type': 'text/html; charset=utf-8'}

@bp.route("/trust")
@bp.route("/trust-center")
def trust_center():
    lang = request.args.get("lang","it")
    if lang == "en":
        titolo = "Trust Center"
        corpo = """<h2>Trust Center</h2>
<p>Matter Lab is built on transparency. This page explains who we are, what data we collect, which AI systems we use, and how we protect your information.</p>

<h3>Who we are</h3>
<p>Matter Lab is an educational tool for F&B professionals developed by Michele Lamorte, Naples, Italy. P.IVA: pending registration.</p>

<h3>AI systems used</h3>
<ul>
<li><strong>Claude Sonnet (Anthropic)</strong> — main chat responses</li>
<li><strong>Claude Haiku (Anthropic)</strong> — quiz generation, fast tasks</li>
<li><strong>Whisper (OpenAI)</strong> — voice transcription (Pro only)</li>
<li><strong>GPT-4o Vision (OpenAI)</strong> — image analysis (Pro only)</li>
<li><strong>Mistral Small</strong> — fallback for fast tasks</li>
<li><strong>OpenAI Embeddings</strong> — semantic search in flavor network</li>
</ul>

<h3>Data we collect</h3>
<ul>
<li>Email address — for authentication only</li>
<li>Questions asked in chat — stored anonymously to improve the service</li>
<li>Notebook entries — saved by the user, visible only to the user</li>
<li>Usage data — chat count, trial status</li>
</ul>

<h3>Data we do NOT collect</h3>
<ul>
<li>Payment data (handled by Stripe, not stored by us)</li>
<li>Location data</li>
<li>Device fingerprinting</li>
<li>Advertising tracking</li>
</ul>

<h3>Data retention</h3>
<p>Account data is retained until you delete your account. Anonymous question logs are retained for 12 months. You can request deletion at any time: <a href="mailto:privacy@matterlab.app">privacy@matterlab.app</a></p>

<h3>AI response disclaimer</h3>
<p>Matter Lab AI responses are generated by language models and may contain errors. They do not replace advice from qualified food technologists or HACCP consultants. Shelf life values are indicative estimates only.</p>

<h3>Sub-processors (GDPR Art. 28)</h3>
<p>Matter Lab uses the following third-party AI providers as sub-processors. Each has an active Data Processing Agreement (DPA) automatically incorporated into their commercial terms of service.</p>
<ul>
<li><strong>Anthropic PBC</strong> (San Francisco, USA) — Claude Sonnet, Claude Haiku. DPA: <a href="https://www.anthropic.com/legal/data-processing-addendum" target="_blank">anthropic.com/legal/dpa</a></li>
<li><strong>OpenAI OpCo LLC</strong> (San Francisco, USA) — Whisper STT, GPT-4o Vision, text-embedding-3-small. DPA: <a href="https://openai.com/policies/data-processing-addendum/" target="_blank">openai.com/policies/dpa</a></li>
<li><strong>Mistral AI SAS</strong> (Paris, France) — Mistral Small fallback. DPA: <a href="https://legal.mistral.ai/terms/data-processing-addendum" target="_blank">legal.mistral.ai/dpa</a></li>
<li><strong>Railway Corp</strong> (San Francisco, USA) — hosting and database infrastructure.</li>
<li><strong>Resend Inc</strong> (San Francisco, USA) — transactional email (verification, password reset).</li>
</ul>
<p>Data processed by these sub-processors consists only of: anonymised chat questions and AI responses. No personal identifiers (email, name) are sent to AI providers.</p>

<h3>Contact</h3>
<p>For privacy, data, or AI-related questions: <a href="mailto:privacy@matterlab.app">privacy@matterlab.app</a></p>"""
    elif lang == "es":
        titolo = "Centro de Confianza"
        corpo = """<h2>Centro de Confianza</h2>
<p>Matter Lab se construye sobre la transparencia. Esta página explica quiénes somos, qué datos recopilamos, qué sistemas de IA utilizamos y cómo protegemos tu información.</p>

<h3>Quiénes somos</h3>
<p>Matter Lab es una herramienta educativa para profesionales F&B desarrollada por Michele Lamorte, Nápoles, Italia.</p>

<h3>Sistemas de IA utilizados</h3>
<ul>
<li><strong>Claude Sonnet (Anthropic)</strong> — respuestas del chat principal</li>
<li><strong>Claude Haiku (Anthropic)</strong> — generación de quiz, tareas rápidas</li>
<li><strong>Whisper (OpenAI)</strong> — transcripción de voz (solo Pro)</li>
<li><strong>GPT-4o Vision (OpenAI)</strong> — análisis de imágenes (solo Pro)</li>
<li><strong>Mistral Small</strong> — fallback para tareas rápidas</li>
<li><strong>OpenAI Embeddings</strong> — búsqueda semántica en la red de sabores</li>
</ul>

<h3>Datos que recopilamos</h3>
<ul>
<li>Dirección de email — solo para autenticación</li>
<li>Preguntas del chat — almacenadas anónimamente para mejorar el servicio</li>
<li>Entradas del cuaderno — guardadas por el usuario, visibles solo para el usuario</li>
<li>Datos de uso — contador de chats, estado del trial</li>
</ul>

<h3>Sub-procesadores (RGPD Art. 28)</h3>
<p>Matter Lab utiliza los siguientes proveedores de IA como sub-procesadores. Cada uno tiene un Acuerdo de Procesamiento de Datos (DPA) activo incorporado en sus términos comerciales de servicio.</p>
<ul>
<li><strong>Anthropic PBC</strong> (San Francisco, EE.UU.) — Claude Sonnet, Claude Haiku. DPA: <a href="https://www.anthropic.com/legal/data-processing-addendum" target="_blank">anthropic.com/legal/dpa</a></li>
<li><strong>OpenAI OpCo LLC</strong> (San Francisco, EE.UU.) — Whisper STT, GPT-4o Vision, text-embedding-3-small. DPA: <a href="https://openai.com/policies/data-processing-addendum/" target="_blank">openai.com/policies/dpa</a></li>
<li><strong>Mistral AI SAS</strong> (París, Francia) — Mistral Small fallback. DPA: <a href="https://legal.mistral.ai/terms/data-processing-addendum" target="_blank">legal.mistral.ai/dpa</a></li>
<li><strong>Railway Corp</strong> (San Francisco, EE.UU.) — hosting e infraestructura de base de datos.</li>
<li><strong>Resend Inc</strong> (San Francisco, EE.UU.) — email transaccional (verificación, recuperación de contraseña).</li>
</ul>
<p>Los datos procesados por estos sub-procesadores consisten únicamente en: preguntas de chat anonimizadas y respuestas de IA. Ningún identificador personal (email, nombre) se envía a los proveedores de IA.</p>

<h3>Contacto</h3>
<p>Para preguntas sobre privacidad o IA: <a href="mailto:privacy@matterlab.app">privacy@matterlab.app</a></p>"""
    else:
        titolo = "Trust Center"
        corpo = """<h2>Trust Center</h2>
<p>Matter Lab è costruito sulla trasparenza. Questa pagina spiega chi siamo, quali dati raccogliamo, quali sistemi AI utilizziamo e come proteggiamo le tue informazioni.</p>

<h3>Chi siamo</h3>
<p>Matter Lab è uno strumento educativo per professionisti F&B sviluppato da Michele Lamorte, Napoli, Italia. P.IVA: in fase di registrazione.</p>

<h3>Sistemi AI utilizzati</h3>
<ul>
<li><strong>Claude Sonnet (Anthropic)</strong> — risposte chat principali</li>
<li><strong>Claude Haiku (Anthropic)</strong> — generazione quiz, task veloci</li>
<li><strong>Whisper (OpenAI)</strong> — trascrizione vocale (solo Pro)</li>
<li><strong>GPT-4o Vision (OpenAI)</strong> — analisi foto schede tecniche (solo Pro)</li>
<li><strong>Mistral Small</strong> — fallback per task veloci</li>
<li><strong>OpenAI Embeddings</strong> — ricerca semantica nel flavor network</li>
</ul>

<h3>Dati che raccogliamo</h3>
<ul>
<li>Indirizzo email — solo per autenticazione</li>
<li>Domande poste in chat — conservate in forma anonima per migliorare il servizio</li>
<li>Voci del Quaderno — salvate dall'utente, visibili solo all'utente</li>
<li>Dati di utilizzo — contatore chat, stato trial</li>
</ul>

<h3>Dati che NON raccogliamo</h3>
<ul>
<li>Dati di pagamento (gestiti da Stripe, non conservati da noi)</li>
<li>Dati di geolocalizzazione</li>
<li>Device fingerprinting</li>
<li>Tracking pubblicitario</li>
</ul>

<h3>Conservazione dati</h3>
<p>I dati dell'account vengono conservati fino alla cancellazione. I log anonimi delle domande vengono conservati per 12 mesi. Puoi richiedere la cancellazione in qualsiasi momento: <a href="mailto:privacy@matterlab.app">privacy@matterlab.app</a></p>

<h3>Disclaimer risposte AI</h3>
<p>Le risposte AI di Matter Lab sono generate da modelli linguistici e possono contenere errori. Non sostituiscono il parere di tecnici alimentari o consulenti HACCP qualificati. I valori di shelf life sono stime orientative.</p>

<h3>Sub-responsabili del trattamento (GDPR Art. 28)</h3>
<p>Matter Lab si avvale dei seguenti fornitori AI come sub-responsabili del trattamento. Ciascuno dispone di un Data Processing Agreement (DPA) attivo, automaticamente incorporato nei propri termini commerciali di servizio.</p>
<ul>
<li><strong>Anthropic PBC</strong> (San Francisco, USA) — Claude Sonnet, Claude Haiku. DPA: <a href="https://www.anthropic.com/legal/data-processing-addendum" target="_blank">anthropic.com/legal/dpa</a></li>
<li><strong>OpenAI OpCo LLC</strong> (San Francisco, USA) — Whisper STT, GPT-4o Vision, text-embedding-3-small. DPA: <a href="https://openai.com/policies/data-processing-addendum/" target="_blank">openai.com/policies/dpa</a></li>
<li><strong>Mistral AI SAS</strong> (Parigi, Francia) — Mistral Small fallback. DPA: <a href="https://legal.mistral.ai/terms/data-processing-addendum" target="_blank">legal.mistral.ai/dpa</a></li>
<li><strong>Railway Corp</strong> (San Francisco, USA) — hosting e infrastruttura database.</li>
<li><strong>Resend Inc</strong> (San Francisco, USA) — email transazionali (verifica account, reset password).</li>
</ul>
<p>I dati trasmessi a questi sub-responsabili consistono esclusivamente in: domande chat anonimizzate e risposte AI. Nessun identificatore personale (email, nome) viene inviato ai provider AI.</p>

<h3>Contatti</h3>
<p>Per domande su privacy, dati o AI: <a href="mailto:privacy@matterlab.app">privacy@matterlab.app</a></p>"""
    return _pagina_legale(titolo, corpo)

@bp.route("/cookie-policy")
def cookie_policy():
    lang = request.args.get("lang","it")
    if lang == "en":
        titolo = "Cookie Policy"
        corpo = """<h2>Cookie Policy</h2>
<p>Matter Lab uses only technical cookies necessary for the service to function. No profiling or advertising cookies are used.</p>
<h3>Cookies used</h3>
<ul>
<li><strong>matter_token</strong> — authentication token, stored in localStorage. Duration: session.</li>
<li><strong>ml_lang</strong> — language preference. Duration: persistent.</li>
<li><strong>matter_disc</strong> — selected discipline. Duration: persistent.</li>
</ul>
<p>No third-party cookies. No data shared with advertising platforms.</p>
<p>For information: <a href="mailto:privacy@matterlab.app">privacy@matterlab.app</a></p>"""
    elif lang == "es":
        titolo = "Política de Cookies"
        corpo = """<h2>Política de Cookies</h2>
<p>Matter Lab utiliza únicamente cookies técnicas necesarias para el funcionamiento del servicio. No se utilizan cookies de perfilado ni publicitarias.</p>
<h3>Cookies utilizadas</h3>
<ul>
<li><strong>matter_token</strong> — token de autenticación, almacenado en localStorage. Duración: sesión.</li>
<li><strong>ml_lang</strong> — preferencia de idioma. Duración: persistente.</li>
<li><strong>matter_disc</strong> — disciplina seleccionada. Duración: persistente.</li>
</ul>
<p>Sin cookies de terceros. Sin datos compartidos con plataformas publicitarias.</p>"""
    else:
        titolo = "Cookie Policy"
        corpo = """<h2>Cookie Policy</h2>
<p>Matter Lab utilizza esclusivamente cookie tecnici necessari al funzionamento del servizio. Non vengono utilizzati cookie di profilazione né pubblicitari.</p>
<h3>Cookie utilizzati</h3>
<ul>
<li><strong>matter_token</strong> — token di autenticazione, memorizzato in localStorage. Durata: sessione.</li>
<li><strong>ml_lang</strong> — preferenza lingua. Durata: persistente.</li>
<li><strong>matter_disc</strong> — disciplina selezionata. Durata: persistente.</li>
</ul>
<p>Nessun cookie di terze parti. Nessun dato condiviso con piattaforme pubblicitarie.</p>
<p>Per informazioni: <a href="mailto:privacy@matterlab.app">privacy@matterlab.app</a></p>"""
    return _pagina_legale(titolo, corpo)

@bp.route("/come-funziona-ai")
def come_funziona_ai():
    lang = request.args.get("lang","it")
    if lang == "es":
        titolo = "Cómo funciona la IA"
        corpo = """<h2>Cómo funciona la IA de Matter Lab</h2>
<p>Matter Lab utiliza modelos de lenguaje IA para responder tus preguntas sobre ciencia gastronómica.</p>
<h3>Modelos utilizados</h3>
<ul>
<li><strong>Claude (Anthropic)</strong> — chat principal. Responde sobre fenómenos físicos y químicos.</li>
<li><strong>Haiku (Anthropic)</strong> — generación de quiz y traducciones rápidas.</li>
<li><strong>Whisper (OpenAI)</strong> — transcripción de voz (solo Pro).</li>
<li><strong>GPT-4o Vision (OpenAI)</strong> — análisis de fotos de fichas técnicas (solo Pro).</li>
</ul>
<h3>Qué hace y no hace la IA</h3>
<ul>
<li>La IA responde basándose en el grafo de conocimiento de Matter Lab (fenómenos físicos, números objetivo).</li>
<li>La IA no reemplaza a un tecnólogo alimentario ni a un consultor HACCP.</li>
<li>Los valores de vida útil son estimaciones orientativas, no certificaciones.</li>
<li>Cada respuesta de IA incluye un aviso legal.</li>
</ul>
<h3>Tus datos</h3>
<p>Las preguntas se registran de forma anónima para mejorar el servicio. Ningún dato personal se comparte con los proveedores de IA más allá de lo necesario para generar la respuesta.</p>
<p>EU AI Act: Matter Lab es una herramienta de IA de uso general para formación profesional.</p>"""
    elif lang == "en":
        titolo = "How the AI works"
        corpo = """<h2>How Matter Lab AI works</h2>
<p>Matter Lab uses AI language models to answer your questions about food science.</p>
<h3>Models used</h3>
<ul>
<li><strong>Claude (Anthropic)</strong> — main chat. Answers questions about physical and chemical phenomena.</li>
<li><strong>Haiku (Anthropic)</strong> — quiz generation and fast translations.</li>
<li><strong>Whisper (OpenAI)</strong> — voice transcription (Pro only).</li>
<li><strong>GPT-4o Vision (OpenAI)</strong> — image analysis of technical sheets (Pro only).</li>
</ul>
<h3>What AI does and does not do</h3>
<ul>
<li>AI answers based on the Matter Lab knowledge graph (physical phenomena, target numbers, scientific principles).</li>
<li>AI does not replace a food technologist or HACCP consultant.</li>
<li>Shelf life values are indicative estimates, not certifications.</li>
<li>Every AI response includes a disclaimer.</li>
</ul>
<h3>Your data</h3>
<p>Questions are logged anonymously to improve the service. No personal data is shared with AI providers beyond what is necessary to generate the response.</p>
<p>EU AI Act: Matter Lab is a general-purpose AI tool for professional education. It does not make autonomous decisions affecting people.</p>"""
    else:
        titolo = "Come funziona l'AI"
        corpo = """<h2>Come funziona l'AI di Matter Lab</h2>
<p>Matter Lab utilizza modelli linguistici AI per rispondere alle tue domande sulla scienza degli alimenti.</p>
<h3>Modelli utilizzati</h3>
<ul>
<li><strong>Claude (Anthropic)</strong> — chat principale. Risponde alle domande sui fenomeni fisici e chimici.</li>
<li><strong>Haiku (Anthropic)</strong> — generazione quiz e traduzioni rapide.</li>
<li><strong>Whisper (OpenAI)</strong> — trascrizione vocale (solo Pro).</li>
<li><strong>GPT-4o Vision (OpenAI)</strong> — analisi foto schede tecniche (solo Pro).</li>
</ul>
<h3>Cosa fa e non fa l'AI</h3>
<ul>
<li>L'AI risponde basandosi sul grafo di conoscenza di Matter Lab (fenomeni fisici, numeri bersaglio, principi scientifici).</li>
<li>L'AI non sostituisce un tecnologo alimentare né un consulente HACCP.</li>
<li>I valori di shelf life sono stime orientative, non certificazioni.</li>
<li>Ogni risposta AI include un disclaimer.</li>
</ul>
<h3>I tuoi dati</h3>
<p>Le domande vengono registrate in forma anonima per migliorare il servizio. Nessun dato personale viene condiviso con i provider AI oltre a quanto necessario per generare la risposta.</p>
<p>EU AI Act: Matter Lab è uno strumento AI a uso generale per la formazione professionale. Non prende decisioni autonome che riguardano le persone.</p>"""
    return _pagina_legale(titolo, corpo)

def _pagina_legale(titolo, corpo):
    """Wrapper HTML per pagine legali."""
    return f"""<!DOCTYPE html>
<html lang="it"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{titolo} — Matter Lab</title>
<style>
body{{font-family:sans-serif;background:#FAF6EE;color:#1A1A18;max-width:680px;margin:0 auto;padding:30px 20px}}
h1{{font-family:Georgia,serif;color:#2C6E63;font-size:22px;margin-bottom:4px}}
h2{{font-family:Georgia,serif;font-size:18px;margin-top:28px}}
h3{{font-size:14px;font-weight:600;margin-top:20px;color:#2C6E63}}
p,li{{font-size:14px;line-height:1.7;color:#3A3830}}
a{{color:#2C6E63}}
.back{{display:inline-block;margin-bottom:20px;color:#2C6E63;text-decoration:none;font-size:13px}}
</style>
</head><body>
<a href="/app" class="back">← Matter Lab</a>
<h1>Matter Lab</h1>
{corpo}
<p style="margin-top:40px;font-size:12px;color:#999">Ultimo aggiornamento: luglio 2026</p>
</body></html>"""

@bp.route("/termini")
def termini():
    """LE3 — Termini di servizio."""
    return """<!DOCTYPE html><html lang="it"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Termini di Servizio — Matter</title>
<style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;padding:0 20px;line-height:1.7;color:#1A1A18}
h1{font-size:24px}h2{font-size:18px;margin-top:32px}p,li{font-size:15px}</style>
</head><body>
<h1>Termini di Servizio — Matter</h1>
<p><strong>Ultimo aggiornamento:</strong> luglio 2026</p>
<h2>Cosa è Matter</h2>
<p>Matter è uno strumento informativo di supporto per professionisti F&B. Le risposte sono generate da modelli AI (Anthropic/Mistral) sulla base di un grafo di conoscenza scientifica verificata.</p>
<h2>Limitazioni di responsabilità</h2>
<p>Le informazioni fornite da Matter hanno scopo esclusivamente informativo e didattico. Non sostituiscono la competenza professionale, la consulenza di esperti alimentari o le normative vigenti in materia di sicurezza alimentare (HACCP). L'utente è l'unico responsabile delle decisioni operative prese sulla base delle informazioni ricevute.</p>
<h2>Flavor network</h2>
<p>Gli abbinamenti suggeriti dal flavor network sono ipotesi basate su composti volatili condivisi (dataset scientifico Ahn 2011). Non costituiscono garanzie nutrizionali, mediche o di sicurezza alimentare.</p>
<h2>Account e abbonamento</h2>
<p>Il piano Free è gratuito e include funzionalità limitate. Il piano Pro è a pagamento (€19,99/mese) e include l'accesso completo al grafo, alla chat AI e al flavor network. L'abbonamento è rinnovabile mensilmente e cancellabile in qualsiasi momento.</p>
<h2>Proprietà intellettuale</h2>
<p>Il grafo di conoscenza, il codice e il design di Matter sono proprietà del titolare. I dati scientifici provengono da fonti pubbliche citate (dataset Ahn CC BY, PubChem NCBI).</p>
<p><a href="/">← Torna a Matter</a></p>
</body></html>""", 200, {'Content-Type': 'text/html; charset=utf-8'}
