-- Schema della tabella `ricette` (separata dal grafo nodes/edges).
-- Versionato dallo schema reale del DB live (2026-10-10). Idempotente: non tocca i dati.
CREATE TABLE IF NOT EXISTS ricette (
  id text NOT NULL,
  nome text NOT NULL,
  disciplina text NOT NULL,
  descrizione text,
  ingredienti jsonb,
  fenomeni jsonb,
  numeri jsonb,
  punto_critico text,
  scheda_en text,
  scheda_es text,
  ts timestamptz DEFAULT now(),
  tecniche jsonb,
  abbinamenti jsonb,
  vino_birra jsonb,
  procedimento jsonb,
  immagine text,
  immagine_autore text,
  immagine_url_fonte text,
  tempo_prep integer,
  tempo_cottura integer,
  difficolta text,
  porzioni text,
  applicazioni jsonb,
  twist_di text,
  nome_en text,
  nome_es text,
  procedimento_en jsonb,
  procedimento_es jsonb,
  applicazioni_en jsonb,
  applicazioni_es jsonb,
  punto_critico_en text,
  punto_critico_es text,
  esperimento text,
  limite text,
  esperimento_en text,
  esperimento_es text,
  limite_en text,
  limite_es text,
  twist text,
  twist_en text,
  twist_es text,
  recipe_type text DEFAULT 'madre',
  parent_recipe_id text,
  variante_di text,
  hero_subject text,
  hero_style text,
  hero_prompt text,
  portata text,
  pubblica boolean DEFAULT false,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_ricette_parent ON ricette (parent_recipe_id);
CREATE INDEX IF NOT EXISTS idx_ricette_type ON ricette (recipe_type);